package org.casa.backend.enums;

public enum Municipio {
    ABEJONES("Abejones"),
    ACATLAN_DE_PEREZ_FIGUEROA("Acatlán de Pérez Figueroa"),
    ASUNCION_CACALOTEPEC("Asunción Cacalotepec"),
    ASUNCION_CUYOTEPEJI("Asunción Cuyotepeji"),
    ASUNCION_IXTALTEPEC("Asunción Ixtaltepec"),
    ASUNCION_NOCHIXTLAN("Asunción Nochixtlán"),
    ASUNCION_OCOTLAN("Asunción Ocotlán"),
    ASUNCION_TLACOLULITA("Asunción Tlacolulita"),
    AYOTZINTEPEC("Ayotzintepec"),
    EL_BARRIO_DE_LA_SOLEDAD("El Barrio de la Soledad"),
    CALIHUALA("Calihualá"),
    CANDELARIA_LOXICHA("Candelaria Loxicha"),
    CIENEGA_DE_ZIMATLAN("Ciénega de Zimatlán"),
    CIUDAD_IXTEPEC("Ciudad Ixtepec"),
    COATECAS_ALTAS("Coatecas Altas"),
    COICOYAN_DE_LAS_FLORES("Coicoyán de las Flores"),
    LA_COMPANIA("La Compañía"),
    CONCEPCION_BUENAVISTA("Concepción Buenavista"),
    CONCEPCION_PAPALO("Concepción Pápalo"),
    CONSTANCIA_DEL_ROSARIO("Constancia del Rosario"),
    COSOLAPA("Cosolapa"),
    COSOLTEPEC("Cosoltepec"),
    CUILAPAM_DE_GUERRERO("Cuilápam de Guerrero"),
    CUYAMECALCO_VILLA_DE_ZARAGOZA("Cuyamecalco Villa de Zaragoza"),
    CHAHUITES("Chahuites"),
    CHALCATONGO_DE_HIDALGO("Chalcatongo de Hidalgo"),
    CHIQUIHUITLAN_DE_BENITO_JUAREZ("Chiquihuitlán de Benito Juárez"),
    HEROICA_CIUDAD_DE_EJUTLA_DE_CRESPO("Heroica Ciudad de Ejutla de Crespo"),
    ELOXOCHITLAN_DE_FLORES_MAGON("Eloxochitlán de Flores Magón"),
    EL_ESPINAL("El Espinal"),
    TAMAZULAPAM_DEL_ESPIRITU_SANTO("Tamazulápam del Espíritu Santo"),
    FRESNILLO_DE_TRUJANO("Fresnillo de Trujano"),
    GUADALUPE_ETLA("Guadalupe Etla"),
    GUADALUPE_DE_RAMIREZ("Guadalupe de Ramírez"),
    GUELATAO_DE_JUAREZ("Guelatao de Juárez"),
    GUEVEA_DE_HUMBOLDT("Guevea de Humboldt"),
    MESONES_HIDALGO("Mesones Hidalgo"),
    VILLA_HIDALGO("Villa Hidalgo"),
    HEROICA_CIUDAD_DE_HUAJUAPAN_DE_LEON("Heroica Ciudad de Huajuapan de León"),
    HUAUTEPEC("Huautepec"),
    HUAUTLA_DE_JIMENEZ("Huautla de Jiménez"),
    IXTLAN_DE_JUAREZ("Ixtlán de Juárez"),
    HEROICA_CIUDAD_DE_JUCHITAN_DE_ZARAGOZA("Heroica Ciudad de Juchitán de Zaragoza"),
    LOMA_BONITA("Loma Bonita"),
    MAGDALENA_APASCO("Magdalena Apasco"),
    MAGDALENA_JALTEPEC("Magdalena Jaltepec"),
    SANTA_MAGDALENA_JICOTLAN("Santa Magdalena Jicotlán"),
    MAGDALENA_MIXTEPEC("Magdalena Mixtepec"),
    MAGDALENA_OCOTLAN("Magdalena Ocotlán"),
    MAGDALENA_PENASCO("Magdalena Peñasco"),
    MAGDALENA_TEITIPAC("Magdalena Teitipac"),
    MAGDALENA_TEQUISISTLAN("Magdalena Tequisistlán"),
    MAGDALENA_TLACOTEPEC("Magdalena Tlacotepec"),
    MAGDALENA_ZAHUATLAN("Magdalena Zahuatlán"),
    MARISCALA_DE_JUAREZ("Mariscala de Juárez"),
    MARTIRES_DE_TACUBAYA("Mártires de Tacubaya"),
    MATIAS_ROMERO_AVENDANO("Matías Romero Avendaño"),
    MAZATLAN_VILLA_DE_FLORES("Mazatlán Villa de Flores"),
    MIAHUATLAN_DE_PORFIRIO_DIAZ("Miahuatlán de Porfirio Díaz"),
    MIXISTLAN_DE_LA_REFORMA("Mixistlán de la Reforma"),
    MONJAS("Monjas"),
    NATIVIDAD("Natividad"),
    NAZARENO_ETLA("Nazareno Etla"),
    NEJAPA_DE_MADERO("Nejapa de Madero"),
    IXPANTEPEC_NIEVES("Ixpantepec Nieves"),
    SANTIAGO_NILTEPEC("Santiago Niltepec"),
    OAXACA_DE_JUAREZ("Oaxaca de Juárez"),
    OCOTLAN_DE_MORELOS("Ocotlán de Morelos"),
    LA_PE("La Pe"),
    PINOTEPA_DE_DON_LUIS("Pinotepa de Don Luis"),
    PLUMA_HIDALGO("Pluma Hidalgo"),
    SAN_JOSE_DEL_PROGRESO("San José del Progreso"),
    PUTLA_VILLA_DE_GUERRERO("Putla Villa de Guerrero"),
    SANTA_CATARINA_QUIOQUITANI("Santa Catarina Quioquitani"),
    REFORMA_DE_PINEDA("Reforma de Pineda"),
    LA_REFORMA("La Reforma"),
    REYES_ETLA("Reyes Etla"),
    ROJAS_DE_CUAUHTEMOC("Rojas de Cuauhtémoc"),
    SALINA_CRUZ("Salina Cruz"),
    SAN_AGUSTIN_AMATENGO("San Agustín Amatengo"),
    SAN_AGUSTIN_ATENANGO("San Agustín Atenango"),
    SAN_AGUSTIN_CHAYUCO("San Agustín Chayuco"),
    SAN_AGUSTIN_DE_LAS_JUNTAS("San Agustín de las Juntas"),
    SAN_AGUSTIN_ETLA("San Agustín Etla"),
    SAN_AGUSTIN_LOXICHA("San Agustín Loxicha"),
    SAN_AGUSTIN_TLACOTEPEC("San Agustín Tlacotepec"),
    SAN_AGUSTIN_YATARENI("San Agustín Yatareni"),
    SAN_ANDRES_CABECERA_NUEVA("San Andrés Cabecera Nueva"),
    SAN_ANDRES_DINICUITI("San Andrés Dinicuiti"),
    SAN_ANDRES_HUAXPALTEPEC("San Andrés Huaxpaltepec"),
    SAN_ANDRES_HUAYAPAM("San Andrés Huayápam"),
    SAN_ANDRES_IXTLAHUACA("San Andrés Ixtlahuaca"),
    SAN_ANDRES_LAGUNAS("San Andrés Lagunas"),
    SAN_ANDRES_NUXINO("San Andrés Nuxiño"),
    SAN_ANDRES_PAXTLAN("San Andrés Paxtlán"),
    SAN_ANDRES_SINAXTLA("San Andrés Sinaxtla"),
    SAN_ANDRES_SOLAGA("San Andrés Solaga"),
    SAN_ANDRES_TEOTILALPAM("San Andrés Teotilálpam"),
    SAN_ANDRES_TEPETLAPA("San Andrés Tepetlapa"),
    SAN_ANDRES_YAA("San Andrés Yaá"),
    SAN_ANDRES_ZABACHE("San Andrés Zabache"),
    SAN_ANDRES_ZAUTLA("San Andrés Zautla"),
    SAN_ANTONINO_CASTILLO_VELASCO("San Antonino Castillo Velasco"),
    SAN_ANTONINO_EL_ALTO("San Antonino el Alto"),
    SAN_ANTONINO_MONTE_VERDE("San Antonino Monte Verde"),
    SAN_ANTONIO_ACUTLA("San Antonio Acutla"),
    SAN_ANTONIO_DE_LA_CAL("San Antonio de la Cal"),
    SAN_ANTONIO_HUITEPEC("San Antonio Huitepec"),
    SAN_ANTONIO_NANAHUATIPAM("San Antonio Nanahuatípam"),
    SAN_ANTONIO_SINICAHUA("San Antonio Sinicahua"),
    SAN_ANTONIO_TEPETLAPA("San Antonio Tepetlapa"),
    SAN_BALTAZAR_CHICHICAPAM("San Baltazar Chichicápam"),
    SAN_BALTAZAR_LOXICHA("San Baltazar Loxicha"),
    SAN_BALTAZAR_YATZACHI_EL_BAJO("San Baltazar Yatzachi el Bajo"),
    SAN_BARTOLO_COYOTEPEC("San Bartolo Coyotepec"),
    SAN_BARTOLOME_AYAUTLA("San Bartolomé Ayautla"),
    SAN_BARTOLOME_LOXICHA("San Bartolomé Loxicha"),
    SAN_BARTOLOME_QUIALANA("San Bartolomé Quialana"),
    SAN_BARTOLOME_YUCUANE("San Bartolomé Yucuañe"),
    SAN_BARTOLOME_ZOOGOCHO("San Bartolomé Zoogocho"),
    SAN_BARTOLO_SOYALTEPEC("San Bartolo Soyaltepec"),
    SAN_BARTOLO_YAUTEPEC("San Bartolo Yautepec"),
    SAN_BERNARDO_MIXTEPEC("San Bernardo Mixtepec"),
    SAN_BLAS_ATEMPA("San Blas Atempa"),
    SAN_CARLOS_YAUTEPEC("San Carlos Yautepec"),
    SAN_CRISTOBAL_AMATLAN("San Cristóbal Amatlán"),
    SAN_CRISTOBAL_AMOLTEPEC("San Cristóbal Amoltepec"),
    SAN_CRISTOBAL_LACHIRIOAG("San Cristóbal Lachirioag"),
    SAN_CRISTOBAL_SUCHIXTLAHUACA("San Cristóbal Suchixtlahuaca"),
    SAN_DIONISIO_DEL_MAR("San Dionisio del Mar"),
    SAN_DIONISIO_OCOTEPEC("San Dionisio Ocotepec"),
    SAN_DIONISIO_OCOTLAN("San Dionisio Ocotlán"),
    SAN_ESTEBAN_ATATLAHUCA("San Esteban Atatlahuca"),
    SAN_FELIPE_JALAPA_DE_DIAZ("San Felipe Jalapa de Díaz"),
    SAN_FELIPE_TEJALAPAM("San Felipe Tejalápam"),
    SAN_FELIPE_USILA("San Felipe Usila"),
    SAN_FRANCISCO_CAHUACUA("San Francisco Cahuacuá"),
    SAN_FRANCISCO_CAJONOS("San Francisco Cajonos"),
    SAN_FRANCISCO_CHAPULAPA("San Francisco Chapulapa"),
    SAN_FRANCISCO_CHINDUA("San Francisco Chindúa"),
    SAN_FRANCISCO_DEL_MAR("San Francisco del Mar"),
    SAN_FRANCISCO_HUEHUETLAN("San Francisco Huehuetlán"),
    SAN_FRANCISCO_IXHUATAN("San Francisco Ixhuatán"),
    SAN_FRANCISCO_JALTEPETONGO("San Francisco Jaltepetongo"),
    SAN_FRANCISCO_LACHIGOLO("San Francisco Lachigoló"),
    SAN_FRANCISCO_LOGUECHE("San Francisco Logueche"),
    SAN_FRANCISCO_NUXANO("San Francisco Nuxaño"),
    SAN_FRANCISCO_OZOLOTEPEC("San Francisco Ozolotepec"),
    SAN_FRANCISCO_SOLA("San Francisco Sola"),
    SAN_FRANCISCO_TELIXTLAHUACA("San Francisco Telixtlahuaca"),
    SAN_FRANCISCO_TEOPAN("San Francisco Teopan"),
    SAN_FRANCISCO_TLAPANCINGO("San Francisco Tlapancingo"),
    SAN_GABRIEL_MIXTEPEC("San Gabriel Mixtepec"),
    SAN_ILDEFONSO_AMATLAN("San Ildefonso Amatlán"),
    SAN_ILDEFONSO_SOLA("San Ildefonso Sola"),
    SAN_ILDEFONSO_VILLA_ALTA("San Ildefonso Villa Alta"),
    SAN_JACINTO_AMILPAS("San Jacinto Amilpas"),
    SAN_JACINTO_TLACOTEPEC("San Jacinto Tlacotepec"),
    SAN_JERONIMO_COATLAN("San Jerónimo Coatlán"),
    SAN_JERONIMO_SILACAYOAPILLA("San Jerónimo Silacayoapilla"),
    SAN_JERONIMO_SOSOLA("San Jerónimo Sosola"),
    SAN_JERONIMO_TAVICHE("San Jerónimo Taviche"),
    SAN_JERONIMO_TECOATL("San Jerónimo Tecóatl"),
    SAN_JORGE_NUCHITA("San Jorge Nuchita"),
    SAN_JOSE_AYUQUILA("San José Ayuquila"),
    SAN_JOSE_CHILTEPEC("San José Chiltepec"),
    SAN_JOSE_DEL_PENASCO("San José del Peñasco"),
    SAN_JOSE_ESTANCIA_GRANDE("San José Estancia Grande"),
    SAN_JOSE_INDEPENDENCIA("San José Independencia"),
    SAN_JOSE_LACHIGUIRI("San José Lachiguiri"),
    SAN_JOSE_TENANGO("San José Tenango"),
    SAN_JUAN_ACHIUTLA("San Juan Achiutla"),
    SAN_JUAN_ATEPEC("San Juan Atepec"),
    ANIMAS_TRUJANO("Ánimas Trujano"),
    SAN_JUAN_BAUTISTA_ATATLAHUCA("San Juan Bautista Atatlahuca"),
    SAN_JUAN_BAUTISTA_COIXTLAHUACA("San Juan Bautista Coixtlahuaca"),
    SAN_JUAN_BAUTISTA_CUICATLAN("San Juan Bautista Cuicatlán"),
    SAN_JUAN_BAUTISTA_GUELACHE("San Juan Bautista Guelache"),
    SAN_JUAN_BAUTISTA_JAYACATLAN("San Juan Bautista Jayacatlán"),
    SAN_JUAN_BAUTISTA_LO_DE_SOTO("San Juan Bautista Lo de Soto"),
    SAN_JUAN_BAUTISTA_SUCHITEPEC("San Juan Bautista Suchitepec"),
    SAN_JUAN_BAUTISTA_TLACOATZINTEPEC("San Juan Bautista Tlacoatzintepec"),
    SAN_JUAN_BAUTISTA_TLACHICHILCO("San Juan Bautista Tlachichilco"),
    SAN_JUAN_BAUTISTA_TUXTEPEC("San Juan Bautista Tuxtepec"),
    SAN_JUAN_CACAHUATEPEC("San Juan Cacahuatepec"),
    SAN_JUAN_CIENEGUILLA("San Juan Cieneguilla"),
    SAN_JUAN_COATZOSPAM("San Juan Coatzóspam"),
    SAN_JUAN_COLORADO_("San Juan Colorado "),
    SAN_JUAN_COMALTEPEC("San Juan Comaltepec"),
    SAN_JUAN_COTZOCON("San Juan Cotzocón"),
    SAN_JUAN_CHICOMEZUCHIL("San Juan Chicomezúchil"),
    SAN_JUAN_CHILATECA("San Juan Chilateca"),
    SAN_JUAN_DEL_ESTADO("San Juan del Estado"),
    SAN_JUAN_DEL_RIO("San Juan del Rio"),
    SAN_JUAN_DIUXI("San Juan Diuxi"),
    SAN_JUAN_EVANGELISTA_ANALCO("San Juan Evangelista Analco"),
    SAN_JUAN_GUELAVIA("San Juan Guelavía"),
    SAN_JUAN_GUICHICOVI("San Juan Guichicovi"),
    SAN_JUAN_IHUALTEPEC("San Juan Ihualtepec"),
    SAN_JUAN_JUQUILA_MIXES("San Juan Juquila Mixes"),
    SAN_JUAN_JUQUILA_VIJANOS("San Juan Juquila Vijanos"),
    SAN_JUAN_LACHAO("San Juan Lachao"),
    SAN_JUAN_LACHIGALLA("San Juan Lachigalla"),
    SAN_JUAN_LAJARCIA("San Juan Lajarcia"),
    SAN_JUAN_LALANA("San Juan Lalana"),
    SAN_JUAN_DE_LOS_CUES("San Juan de los Cués"),
    SAN_JUAN_MAZATLAN("San Juan Mazatlán"),
    SAN_JUAN_MIXTEPEC_DISTRITO_08("San Juan Mixtepec Distrito 08"),
    SAN_JUAN_MIXTEPEC_DISTRITO_26("San Juan Mixtepec Distrito 26"),
    SAN_JUAN_NUMI("San Juan Ñumí"),
    SAN_JUAN_OZOLOTEPEC("San Juan Ozolotepec"),
    SAN_JUAN_PETLAPA("San Juan Petlapa"),
    SAN_JUAN_QUIAHIJE("San Juan Quiahije"),
    SAN_JUAN_QUIOTEPEC("San Juan Quiotepec"),
    SAN_JUAN_SAYULTEPEC("San Juan Sayultepec"),
    SAN_JUAN_TABAA("San Juan Tabaá"),
    SAN_JUAN_TAMAZOLA("San Juan Tamazola"),
    SAN_JUAN_TEITA("San Juan Teita"),
    SAN_JUAN_TEITIPAC("San Juan Teitipac"),
    SAN_JUAN_TEPEUXILA("San Juan Tepeuxila"),
    SAN_JUAN_TEPOSCOLULA("San Juan Teposcolula"),
    SAN_JUAN_YAEE("San Juan Yaeé"),
    SAN_JUAN_YATZONA("San Juan Yatzona"),
    SAN_JUAN_YUCUITA("San Juan Yucuita"),
    SAN_LORENZO("San Lorenzo"),
    SAN_LORENZO_ALBARRADAS("San Lorenzo Albarradas"),
    SAN_LORENZO_CACAOTEPEC("San Lorenzo Cacaotepec"),
    SAN_LORENZO_CUAUNECUILTITLA("San Lorenzo Cuaunecuiltitla"),
    SAN_LORENZO_TEXMELUCAN("San Lorenzo Texmelúcan"),
    SAN_LORENZO_VICTORIA("San Lorenzo Victoria"),
    SAN_LUCAS_CAMOTLAN("San Lucas Camotlán"),
    SAN_LUCAS_OJITLAN("San Lucas Ojitlán"),
    SAN_LUCAS_QUIAVINI("San Lucas Quiaviní"),
    SAN_LUCAS_ZOQUIAPAM("San Lucas Zoquiápam"),
    SAN_LUIS_AMATLAN("San Luis Amatlán"),
    SAN_MARCIAL_OZOLOTEPEC("San Marcial Ozolotepec"),
    SAN_MARCOS_ARTEAGA("San Marcos Arteaga"),
    SAN_MARTIN_DE_LOS_CANSECOS("San Martín de los Cansecos"),
    SAN_MARTIN_HUAMELULPAM("San Martín Huamelúlpam"),
    SAN_MARTIN_ITUNYOSO("San Martín Itunyoso"),
    SAN_MARTIN_LACHILA("San Martín Lachilá"),
    SAN_MARTIN_PERAS("San Martín Peras"),
    SAN_MARTIN_TILCAJETE("San Martín Tilcajete"),
    SAN_MARTIN_TOXPALAN("San Martín Toxpalan"),
    SAN_MARTIN_ZACATEPEC("San Martín Zacatepec"),
    SAN_MATEO_CAJONOS("San Mateo Cajonos"),
    CAPULALPAM_DE_MENDEZ("Capulálpam de Méndez"),
    SAN_MATEO_DEL_MAR("San Mateo del Mar"),
    SAN_MATEO_YOLOXOCHITLAN("San Mateo Yoloxochitlán"),
    SAN_MATEO_ETLATONGO("San Mateo Etlatongo"),
    SAN_MATEO_NEJAPAM("San Mateo Nejápam"),
    SAN_MATEO_PENASCO("San Mateo Peñasco"),
    SAN_MATEO_PINAS("San Mateo Piñas"),
    SAN_MATEO_RIO_HONDO("San Mateo Río Hondo"),
    SAN_MATEO_SINDIHUI("San Mateo Sindihui"),
    SAN_MATEO_TLAPILTEPEC("San Mateo Tlapiltepec"),
    SAN_MELCHOR_BETAZA("San Melchor Betaza"),
    SAN_MIGUEL_ACHIUTLA("San Miguel Achiutla"),
    SAN_MIGUEL_AHUEHUETITLAN("San Miguel Ahuehuetitlán"),
    SAN_MIGUEL_ALOAPAM("San Miguel Aloápam"),
    SAN_MIGUEL_AMATITLAN("San Miguel Amatitlán"),
    SAN_MIGUEL_AMATLAN("San Miguel Amatlán"),
    SAN_MIGUEL_COATLAN("San Miguel Coatlán"),
    SAN_MIGUEL_CHICAHUA("San Miguel Chicahua"),
    SAN_MIGUEL_CHIMALAPA("San Miguel Chimalapa"),
    SAN_MIGUEL_DEL_PUERTO("San Miguel del Puerto"),
    SAN_MIGUEL_DEL_RIO("San Miguel del Río"),
    SAN_MIGUEL_EJUTLA("San Miguel Ejutla"),
    SAN_MIGUEL_EL_GRANDE("San Miguel el Grande"),
    SAN_MIGUEL_HUAUTLA("San Miguel Huautla"),
    SAN_MIGUEL_MIXTEPEC("San Miguel Mixtepec"),
    SAN_MIGUEL_PANIXTLAHUACA("San Miguel Panixtlahuaca"),
    SAN_MIGUEL_PERAS("San Miguel Peras"),
    SAN_MIGUEL_PIEDRAS("San Miguel Piedras"),
    SAN_MIGUEL_QUETZALTEPEC("San Miguel Quetzaltepec"),
    SAN_MIGUEL_SANTA_FLOR("San Miguel Santa Flor"),
    VILLA_SOLA_DE_VEGA("Villa Sola de Vega"),
    SAN_MIGUEL_SOYALTEPEC("San Miguel Soyaltepec"),
    SAN_MIGUEL_SUCHIXTEPEC("San Miguel Suchixtepec"),
    VILLA_TALEA_DE_CASTRO("Villa Talea de Castro"),
    SAN_MIGUEL_TECOMATLAN("San Miguel Tecomatlán"),
    SAN_MIGUEL_TENANGO("San Miguel Tenango"),
    SAN_MIGUEL_TEQUIXTEPEC("San Miguel Tequixtepec"),
    SAN_MIGUEL_TILQUIAPAM("San Miguel Tilquiápam"),
    SAN_MIGUEL_TLACAMAMA("San Miguel Tlacamama"),
    SAN_MIGUEL_TLACOTEPEC("San Miguel Tlacotepec"),
    SAN_MIGUEL_TULANCINGO("San Miguel Tulancingo"),
    SAN_MIGUEL_YOTAO("San Miguel Yotao"),
    SAN_NICOLAS("San Nicolás"),
    SAN_NICOLAS_HIDALGO("San Nicolás Hidalgo"),
    SAN_PABLO_COATLAN("San Pablo Coatlán"),
    SAN_PABLO_CUATRO_VENADOS("San Pablo Cuatro Venados"),
    SAN_PABLO_ETLA("San Pablo Etla"),
    SAN_PABLO_HUITZO("San Pablo Huitzo"),
    SAN_PABLO_HUIXTEPEC("San Pablo Huixtepec"),
    SAN_PABLO_MACUILTIANGUIS("San Pablo Macuiltianguis"),
    SAN_PABLO_TIJALTEPEC("San Pablo Tijaltepec"),
    SAN_PABLO_VILLA_DE_MITLA("San Pablo Villa de Mitla"),
    SAN_PABLO_YAGANIZA("San Pablo Yaganiza"),
    SAN_PEDRO_AMUZGOS("San Pedro Amuzgos"),
    SAN_PEDRO_APOSTOL("San Pedro Apóstol"),
    SAN_PEDRO_ATOYAC("San Pedro Atoyac"),
    SAN_PEDRO_CAJONOS("San Pedro Cajonos"),
    SAN_PEDRO_COXCALTEPEC_CANTAROS("San Pedro Coxcaltepec Cántaros"),
    SAN_PEDRO_COMITANCILLO("San Pedro Comitancillo"),
    SAN_PEDRO_EL_ALTO("San Pedro el Alto"),
    SAN_PEDRO_HUAMELULA("San Pedro Huamelula"),
    SAN_PEDRO_HUILOTEPEC("San Pedro Huilotepec"),
    SAN_PEDRO_IXCATLAN("San Pedro Ixcatlán"),
    SAN_PEDRO_IXTLAHUACA("San Pedro Ixtlahuaca"),
    SAN_PEDRO_JALTEPETONGO("San Pedro Jaltepetongo"),
    SAN_PEDRO_JICAYAN("San Pedro Jicayán"),
    SAN_PEDRO_JOCOTIPAC("San Pedro Jocotipac"),
    SAN_PEDRO_JUCHATENGO("San Pedro Juchatengo"),
    SAN_PEDRO_MARTIR("San Pedro Mártir"),
    SAN_PEDRO_MARTIR_QUIECHAPA("San Pedro Mártir Quiechapa"),
    SAN_PEDRO_MARTIR_YUCUXACO("San Pedro Mártir Yucuxaco"),
    SAN_PEDRO_MIXTEPEC_DISTRITO_22("San Pedro Mixtepec Distrito 22"),
    SAN_PEDRO_MIXTEPEC_DISTRITO_26("San Pedro Mixtepec Distrito 26"),
    SAN_PEDRO_MOLINOS("San Pedro Molinos"),
    SAN_PEDRO_NOPALA("San Pedro Nopala"),
    SAN_PEDRO_OCOPETATILLO("San Pedro Ocopetatillo"),
    SAN_PEDRO_OCOTEPEC("San Pedro Ocotepec"),
    SAN_PEDRO_POCHUTLA("San Pedro Pochutla"),
    SAN_PEDRO_QUIATONI("San Pedro Quiatoni"),
    SAN_PEDRO_SOCHIAPAM("San Pedro Sochiápam"),
    SAN_PEDRO_TAPANATEPEC("San Pedro Tapanatepec"),
    SAN_PEDRO_TAVICHE("San Pedro Taviche"),
    SAN_PEDRO_TEOZACOALCO("San Pedro Teozacoalco"),
    SAN_PEDRO_TEUTILA("San Pedro Teutila"),
    SAN_PEDRO_TIDAA("San Pedro Tidaá"),
    SAN_PEDRO_TOPILTEPEC("San Pedro Topiltepec"),
    SAN_PEDRO_TOTOLAPAM("San Pedro Totolápam"),
    VILLA_DE_TUTUTEPEC("Villa de Tututepec"),
    SAN_PEDRO_YANERI("San Pedro Yaneri"),
    SAN_PEDRO_YOLOX("San Pedro Yólox"),
    SAN_PEDRO_Y_SAN_PABLO_AYUTLA("San Pedro y San Pablo Ayutla"),
    VILLA_DE_ETLA("Villa de Etla"),
    SAN_PEDRO_Y_SAN_PABLO_TEPOSCOLULA("San Pedro y San Pablo Teposcolula"),
    SAN_PEDRO_Y_SAN_PABLO_TEQUIXTEPEC("San Pedro y San Pablo Tequixtepec"),
    SAN_PEDRO_YUCUNAMA("San Pedro Yucunama"),
    SAN_RAYMUNDO_JALPAN("San Raymundo Jalpan"),
    SAN_SEBASTIAN_ABASOLO("San Sebastián Abasolo"),
    SAN_SEBASTIAN_COATLAN("San Sebastián Coatlán"),
    SAN_SEBASTIAN_IXCAPA("San Sebastián Ixcapa"),
    SAN_SEBASTIAN_NICANANDUTA("San Sebastián Nicananduta"),
    SAN_SEBASTIAN_RIO_HONDO("San Sebastián Río Hondo"),
    SAN_SEBASTIAN_TECOMAXTLAHUACA("San Sebastián Tecomaxtlahuaca"),
    SAN_SEBASTIAN_TEITIPAC("San Sebastián Teitipac"),
    SAN_SEBASTIAN_TUTLA("San Sebastián Tutla"),
    SAN_SIMON_ALMOLONGAS("San Simón Almolongas"),
    SAN_SIMON_ZAHUATLAN("San Simón Zahuatlán"),
    SANTA_ANA("Santa Ana"),
    SANTA_ANA_ATEIXTLAHUACA("Santa Ana Ateixtlahuaca"),
    SANTA_ANA_CUAUHTEMOC("Santa Ana Cuauhtémoc"),
    SANTA_ANA_DEL_VALLE("Santa Ana del Valle"),
    SANTA_ANA_TAVELA("Santa Ana Tavela"),
    SANTA_ANA_TLAPACOYAN("Santa Ana Tlapacoyan"),
    SANTA_ANA_YARENI("Santa Ana Yareni"),
    SANTA_ANA_ZEGACHE("Santa Ana Zegache"),
    SANTA_CATALINA_QUIERI("Santa Catalina Quierí"),
    SANTA_CATARINA_CUIXTLA("Santa Catarina Cuixtla"),
    SANTA_CATARINA_IXTEPEJI("Santa Catarina Ixtepeji"),
    SANTA_CATARINA_JUQUILA("Santa Catarina Juquila"),
    SANTA_CATARINA_LACHATAO("Santa Catarina Lachatao"),
    SANTA_CATARINA_LOXICHA("Santa Catarina Loxicha"),
    SANTA_CATARINA_MECHOACAN("Santa Catarina Mechoacán"),
    SANTA_CATARINA_MINAS("Santa Catarina Minas"),
    SANTA_CATARINA_QUIANE("Santa Catarina Quiané"),
    SANTA_CATARINA_TAYATA("Santa Catarina Tayata"),
    SANTA_CATARINA_TICUA("Santa Catarina Ticuá"),
    SANTA_CATARINA_YOSONOTU("Santa Catarina Yosonotú"),
    SANTA_CATARINA_ZAPOQUILA("Santa Catarina Zapoquila"),
    SANTA_CRUZ_ACATEPEC("Santa Cruz Acatepec"),
    SANTA_CRUZ_AMILPAS("Santa Cruz Amilpas"),
    SANTA_CRUZ_DE_BRAVO("Santa Cruz de Bravo"),
    SANTA_CRUZ_ITUNDUJIA("Santa Cruz Itundujia"),
    SANTA_CRUZ_MIXTEPEC("Santa Cruz Mixtepec"),
    SANTA_CRUZ_NUNDACO("Santa Cruz Nundaco"),
    SANTA_CRUZ_PAPALUTLA("Santa Cruz Papalutla"),
    SANTA_CRUZ_TACACHE_DE_MINA("Santa Cruz Tacache de Mina"),
    SANTA_CRUZ_TACAHUA("Santa Cruz Tacahua"),
    SANTA_CRUZ_TAYATA("Santa Cruz Tayata"),
    SANTA_CRUZ_XITLA("Santa Cruz Xitla"),
    SANTA_CRUZ_XOXOCOTLAN("Santa Cruz Xoxocotlán"),
    SANTA_CRUZ_ZENZONTEPEC("Santa Cruz Zenzontepec"),
    SANTA_GERTRUDIS("Santa Gertrudis"),
    SANTA_INES_DEL_MONTE("Santa Inés del Monte"),
    SANTA_INES_YATZECHE("Santa Inés Yatzeche"),
    SANTA_LUCIA_DEL_CAMINO("Santa Lucía del Camino"),
    SANTA_LUCIA_MIAHUATLAN("Santa Lucía Miahuatlán"),
    SANTA_LUCIA_MONTEVERDE("Santa Lucía Monteverde"),
    SANTA_LUCIA_OCOTLAN("Santa Lucía Ocotlán"),
    SANTA_MARIA_ALOTEPEC("Santa María Alotepec"),
    SANTA_MARIA_APAZCO("Santa María Apazco"),
    SANTA_MARIA_LA_ASUNCION("Santa María la Asunción"),
    HEROICA_CIUDAD_DE_TLAXIACO("Heroica Ciudad de Tlaxiaco"),
    AYOQUEZCO_DE_ALDAMA("Ayoquezco de Aldama"),
    SANTA_MARIA_ATZOMPA("Santa María Atzompa"),
    SANTA_MARIA_CAMOTLAN("Santa María Camotlán"),
    SANTA_MARIA_COLOTEPEC("Santa María Colotepec"),
    SANTA_MARIA_CORTIJO("Santa María Cortijo"),
    SANTA_MARIA_COYOTEPEC("Santa María Coyotepec"),
    SANTA_MARIA_CHACHOAPAM("Santa María Chachoápam"),
    VILLA_DE_CHILAPA_DE_DIAZ("Villa de Chilapa de Díaz"),
    SANTA_MARIA_CHILCHOTLA("Santa María Chilchotla"),
    SANTA_MARIA_CHIMALAPA("Santa María Chimalapa"),
    SANTA_MARIA_DEL_ROSARIO("Santa María del Rosario"),
    SANTA_MARIA_DEL_TULE("Santa María del Tule"),
    SANTA_MARIA_ECATEPEC("Santa María Ecatepec"),
    SANTA_MARIA_GUELACE("Santa María Guelacé"),
    SANTA_MARIA_GUIENAGATI("Santa María Guienagati"),
    SANTA_MARIA_HUATULCO("Santa María Huatulco"),
    SANTA_MARIA_HUAZOLOTITLAN("Santa María Huazolotitlán"),
    SANTA_MARIA_IPALAPA("Santa María Ipalapa"),
    SANTA_MARIA_IXCATLAN("Santa María Ixcatlán"),
    SANTA_MARIA_JACATEPEC("Santa María Jacatepec"),
    SANTA_MARIA_JALAPA_DEL_MARQUES("Santa María Jalapa del Marqués"),
    SANTA_MARIA_JALTIANGUIS("Santa María Jaltianguis"),
    SANTA_MARIA_LACHIXIO("Santa María Lachixío"),
    SANTA_MARIA_MIXTEQUILLA("Santa María Mixtequilla"),
    SANTA_MARIA_NATIVITAS("Santa María Nativitas"),
    SANTA_MARIA_NDUAYACO("Santa María Nduayaco"),
    SANTA_MARIA_OZOLOTEPEC("Santa María Ozolotepec"),
    SANTA_MARIA_PAPALO("Santa María Pápalo"),
    SANTA_MARIA_PENOLES("Santa María Peñoles"),
    SANTA_MARIA_PETAPA("Santa María Petapa"),
    SANTA_MARIA_QUIEGOLANI("Santa María Quiegolani"),
    SANTA_MARIA_SOLA("Santa María Sola"),
    SANTA_MARIA_TATALTEPEC("Santa María Tataltepec"),
    SANTA_MARIA_TECOMAVACA("Santa María Tecomavaca"),
    SANTA_MARIA_TEMAXCALAPA("Santa María Temaxcalapa"),
    SANTA_MARIA_TEMAXCALTEPEC("Santa María Temaxcaltepec"),
    SANTA_MARIA_TEOPOXCO("Santa María Teopoxco"),
    SANTA_MARIA_TEPANTLALI("Santa María Tepantlali"),
    SANTA_MARIA_TEXCATITLAN("Santa María Texcatitlán"),
    SANTA_MARIA_TLAHUITOLTEPEC("Santa María Tlahuitoltepec"),
    SANTA_MARIA_TLALIXTAC("Santa María Tlalixtac"),
    SANTA_MARIA_TONAMECA("Santa María Tonameca"),
    SANTA_MARIA_TOTOLAPILLA("Santa María Totolapilla"),
    SANTA_MARIA_XADANI("Santa María Xadani"),
    SANTA_MARIA_YALINA("Santa María Yalina"),
    SANTA_MARIA_YAVESIA("Santa María Yavesía"),
    SANTA_MARIA_YOLOTEPEC("Santa María Yolotepec"),
    SANTA_MARIA_YOSOYUA("Santa María Yosoyúa"),
    SANTA_MARIA_YUCUHITI("Santa María Yucuhiti"),
    SANTA_MARIA_ZACATEPEC("Santa María Zacatepec"),
    SANTA_MARIA_ZANIZA("Santa María Zaniza"),
    SANTA_MARIA_ZOQUITLAN("Santa María Zoquitlán"),
    SANTIAGO_AMOLTEPEC("Santiago Amoltepec"),
    SANTIAGO_APOALA("Santiago Apoala"),
    SANTIAGO_APOSTOL("Santiago Apóstol"),
    SANTIAGO_ASTATA("Santiago Astata"),
    SANTIAGO_ATITLAN("Santiago Atitlán"),
    SANTIAGO_AYUQUILILLA("Santiago Ayuquililla"),
    SANTIAGO_CACALOXTEPEC("Santiago Cacaloxtepec"),
    SANTIAGO_CAMOTLAN("Santiago Camotlán"),
    SANTIAGO_COMALTEPEC("Santiago Comaltepec"),
    SANTIAGO_CHAZUMBA("Santiago Chazumba"),
    SANTIAGO_CHOAPAM("Santiago Choápam"),
    SANTIAGO_DEL_RIO("Santiago del Río"),
    SANTIAGO_HUAJOLOTITLAN("Santiago Huajolotitlán"),
    SANTIAGO_HUAUCLILLA("Santiago Huauclilla"),
    SANTIAGO_IHUITLAN_PLUMAS("Santiago Ihuitlán Plumas"),
    SANTIAGO_IXCUINTEPEC("Santiago Ixcuintepec"),
    SANTIAGO_IXTAYUTLA("Santiago Ixtayutla"),
    SANTIAGO_JAMILTEPEC("Santiago Jamiltepec"),
    SANTIAGO_JOCOTEPEC("Santiago Jocotepec"),
    SANTIAGO_JUXTLAHUACA("Santiago Juxtlahuaca"),
    SANTIAGO_LACHIGUIRI("Santiago Lachiguiri"),
    SANTIAGO_LALOPA("Santiago Lalopa"),
    SANTIAGO_LAOLLAGA("Santiago Laollaga"),
    SANTIAGO_LAXOPA("Santiago Laxopa"),
    SANTIAGO_LLANO_GRANDE("Santiago Llano Grande"),
    SANTIAGO_MATATLAN("Santiago Matatlán"),
    SANTIAGO_MILTEPEC("Santiago Miltepec"),
    SANTIAGO_MINAS("Santiago Minas"),
    SANTIAGO_NACALTEPEC("Santiago Nacaltepec"),
    SANTIAGO_NEJAPILLA("Santiago Nejapilla"),
    SANTIAGO_NUNDICHE("Santiago Nundiche"),
    SANTIAGO_NUYOO("Santiago Nuyoó"),
    SANTIAGO_PINOTEPA_NACIONAL("Santiago Pinotepa Nacional"),
    SANTIAGO_SUCHILQUITONGO("Santiago Suchilquitongo"),
    SANTIAGO_TAMAZOLA("Santiago Tamazola"),
    SANTIAGO_TAPEXTLA("Santiago Tapextla"),
    VILLA_TEJUPAM_DE_LA_UNION("Villa Tejúpam de la Unión"),
    SANTIAGO_TENANGO("Santiago Tenango"),
    SANTIAGO_TEPETLAPA("Santiago Tepetlapa"),
    SANTIAGO_TETEPEC("Santiago Tetepec"),
    SANTIAGO_TEXCALCINGO("Santiago Texcalcingo"),
    SANTIAGO_TEXTITLAN("Santiago Textitlán"),
    SANTIAGO_TILANTONGO("Santiago Tilantongo"),
    SANTIAGO_TILLO("Santiago Tillo"),
    SANTIAGO_TLAZOYALTEPEC("Santiago Tlazoyaltepec"),
    SANTIAGO_XANICA("Santiago Xanica"),
    SANTIAGO_XIACUI("Santiago Xiacuí"),
    SANTIAGO_YAITEPEC("Santiago Yaitepec"),
    SANTIAGO_YAVEO("Santiago Yaveo"),
    SANTIAGO_YOLOMECATL("Santiago Yolomécatl"),
    SANTIAGO_YOSONDUA("Santiago Yosondúa"),
    SANTIAGO_YUCUYACHI("Santiago Yucuyachi"),
    SANTIAGO_ZACATEPEC("Santiago Zacatepec"),
    SANTIAGO_ZOOCHILA("Santiago Zoochila"),
    NUEVO_ZOQUIAPAM("Nuevo Zoquiápam"),
    SANTO_DOMINGO_INGENIO("Santo Domingo Ingenio"),
    SANTO_DOMINGO_ALBARRADAS("Santo Domingo Albarradas"),
    SANTO_DOMINGO_ARMENTA("Santo Domingo Armenta"),
    SANTO_DOMINGO_CHIHUITAN("Santo Domingo Chihuitán"),
    SANTO_DOMINGO_DE_MORELOS("Santo Domingo de Morelos"),
    SANTO_DOMINGO_IXCATLAN("Santo Domingo Ixcatlán"),
    SANTO_DOMINGO_NUXAA("Santo Domingo Nuxaá"),
    SANTO_DOMINGO_OZOLOTEPEC("Santo Domingo Ozolotepec"),
    SANTO_DOMINGO_PETAPA("Santo Domingo Petapa"),
    SANTO_DOMINGO_ROAYAGA("Santo Domingo Roayaga"),
    SANTO_DOMINGO_TEHUANTEPEC("Santo Domingo Tehuantepec"),
    SANTO_DOMINGO_TEOJOMULCO("Santo Domingo Teojomulco"),
    SANTO_DOMINGO_TEPUXTEPEC("Santo Domingo Tepuxtepec"),
    SANTO_DOMINGO_TLATAYAPAM("Santo Domingo Tlatayápam"),
    SANTO_DOMINGO_TOMALTEPEC("Santo Domingo Tomaltepec"),
    SANTO_DOMINGO_TONALA("Santo Domingo Tonalá"),
    SANTO_DOMINGO_TONALTEPEC("Santo Domingo Tonaltepec"),
    SANTO_DOMINGO_XAGACIA("Santo Domingo Xagacía"),
    SANTO_DOMINGO_YANHUITLAN("Santo Domingo Yanhuitlán"),
    SANTO_DOMINGO_YODOHINO("Santo Domingo Yodohino"),
    SANTO_DOMINGO_ZANATEPEC("Santo Domingo Zanatepec"),
    SANTOS_REYES_NOPALA("Santos Reyes Nopala"),
    SANTOS_REYES_PAPALO("Santos Reyes Pápalo"),
    SANTOS_REYES_TEPEJILLO("Santos Reyes Tepejillo"),
    SANTOS_REYES_YUCUNA("Santos Reyes Yucuná"),
    SANTO_TOMAS_JALIEZA("Santo Tomás Jalieza"),
    SANTO_TOMAS_MAZALTEPEC("Santo Tomás Mazaltepec"),
    SANTO_TOMAS_OCOTEPEC("Santo Tomás Ocotepec"),
    SANTO_TOMAS_TAMAZULAPAN("Santo Tomás Tamazulapan"),
    SAN_VICENTE_COATLAN("San Vicente Coatlán"),
    SAN_VICENTE_LACHIXIO("San Vicente Lachixío"),
    SAN_VICENTE_NUNU("San Vicente Nuñú"),
    SILACAYOAPAM("Silacayoápam"),
    SITIO_DE_XITLAPEHUA("Sitio de Xitlapehua"),
    SOLEDAD_ETLA("Soledad Etla"),
    VILLA_DE_TAMAZULAPAM_DEL_PROGRESO("Villa de Tamazulápam del Progreso"),
    TANETZE_DE_ZARAGOZA("Tanetze de Zaragoza"),
    TANICHE("Taniche"),
    TATALTEPEC_DE_VALDES("Tataltepec de Valdés"),
    TEOCOCUILCO_DE_MARCOS_PEREZ("Teococuilco de Marcos Pérez"),
    TEOTITLAN_DE_FLORES_MAGON("Teotitlán de Flores Magón"),
    TEOTITLAN_DEL_VALLE("Teotitlán del Valle"),
    TEOTONGO("Teotongo"),
    TEPELMEME_VILLA_DE_MORELOS("Tepelmeme Villa de Morelos"),
    HEROICA_VILLA_TEZOATLAN_DE_SEGURA_Y_LUNA("Heroica Villa Tezoatlán de Segura y Luna"),
    SAN_JERONIMO_TLACOCHAHUAYA("San Jerónimo Tlacochahuaya"),
    TLACOLULA_DE_MATAMOROS("Tlacolula de Matamoros"),
    TLACOTEPEC_PLUMAS("Tlacotepec Plumas"),
    TLALIXTAC_DE_CABRERA("Tlalixtac de Cabrera"),
    TOTONTEPEC_VILLA_DE_MORELOS("Totontepec Villa de Morelos"),
    TRINIDAD_ZAACHILA("Trinidad Zaachila"),
    LA_TRINIDAD_VISTA_HERMOSA("La Trinidad Vista Hermosa"),
    UNION_HIDALGO("Unión Hidalgo"),
    VALERIO_TRUJANO("Valerio Trujano"),
    SAN_JUAN_BAUTISTA_VALLE_NACIONAL("San Juan Bautista Valle Nacional"),
    VILLA_DIAZ_ORDAZ("Villa Díaz Ordaz"),
    YAXE("Yaxe"),
    MAGDALENA_YODOCONO_DE_PORFIRIO_DIAZ("Magdalena Yodocono de Porfirio Díaz"),
    YOGANA("Yogana"),
    YUTANDUCHI_DE_GUERRERO("Yutanduchi de Guerrero"),
    VILLA_DE_ZAACHILA("Villa de Zaachila"),
    SAN_MATEO_YUCUTINDOO("San Mateo Yucutindoo"),
    ZAPOTITLAN_LAGUNAS("Zapotitlán Lagunas"),
    ZAPOTITLAN_PALMAS("Zapotitlán Palmas"),
    SANTA_INES_DE_ZARAGOZA("Santa Inés de Zaragoza"),
    ZIMATLAN_DE_ALVAREZ("Zimatlán de Álvarez");

    private final String nombre;

    Municipio(String nombre) {
        this.nombre = nombre;
    }

    public String getNombre() {
        return nombre;
    }

    @Override
    public String toString() {
        return nombre;
    }

}
