package org.casa.backend.enums;

public enum Municipio {
    ABEJONES("Abejones", Estado.OAXACA),
    ACATLAN_DE_PEREZ_FIGUEROA("Acatlán de Pérez Figueroa", Estado.OAXACA),
    ASUNCION_CACALOTEPEC("Asunción Cacalotepec", Estado.OAXACA),
    ASUNCION_CUYOTEPEJI("Asunción Cuyotepeji", Estado.OAXACA),
    ASUNCION_IXTALTEPEC("Asunción Ixtaltepec", Estado.OAXACA),
    ASUNCION_NOCHIXTLAN("Asunción Nochixtlán", Estado.OAXACA),
    ASUNCION_OCOTLAN("Asunción Ocotlán", Estado.OAXACA),
    ASUNCION_TLACOLULITA("Asunción Tlacolulita", Estado.OAXACA),
    AYOTZINTEPEC("Ayotzintepec", Estado.OAXACA),
    EL_BARRIO_DE_LA_SOLEDAD("El Barrio de la Soledad", Estado.OAXACA),
    CALIHUALA("Calihualá", Estado.OAXACA),
    CANDELARIA_LOXICHA("Candelaria Loxicha", Estado.OAXACA),
    CIENEGA_DE_ZIMATLAN("Ciénega de Zimatlán", Estado.OAXACA),
    CIUDAD_IXTEPEC("Ciudad Ixtepec", Estado.OAXACA),
    COATECAS_ALTAS("Coatecas Altas", Estado.OAXACA),
    COICOYAN_DE_LAS_FLORES("Coicoyán de las Flores", Estado.OAXACA),
    LA_COMPANIA("La Compañía", Estado.OAXACA),
    CONCEPCION_BUENAVISTA("Concepción Buenavista", Estado.OAXACA),
    CONCEPCION_PAPALO("Concepción Pápalo", Estado.OAXACA),
    CONSTANCIA_DEL_ROSARIO("Constancia del Rosario", Estado.OAXACA),
    COSOLAPA("Cosolapa", Estado.OAXACA),
    COSOLTEPEC("Cosoltepec", Estado.OAXACA),
    CUILAPAM_DE_GUERRERO("Cuilápam de Guerrero", Estado.OAXACA),
    CUYAMECALCO_VILLA_DE_ZARAGOZA("Cuyamecalco Villa de Zaragoza", Estado.OAXACA),
    CHAHUITES("Chahuites", Estado.OAXACA),
    CHALCATONGO_DE_HIDALGO("Chalcatongo de Hidalgo", Estado.OAXACA),
    CHIQUIHUITLAN_DE_BENITO_JUAREZ("Chiquihuitlán de Benito Juárez", Estado.OAXACA),
    HEROICA_CIUDAD_DE_EJUTLA_DE_CRESPO("Heroica Ciudad de Ejutla de Crespo", Estado.OAXACA),
    ELOXOCHITLAN_DE_FLORES_MAGON("Eloxochitlán de Flores Magón", Estado.OAXACA),
    EL_ESPINAL("El Espinal", Estado.OAXACA),
    TAMAZULAPAM_DEL_ESPIRITU_SANTO("Tamazulápam del Espíritu Santo", Estado.OAXACA),
    FRESNILLO_DE_TRUJANO("Fresnillo de Trujano", Estado.OAXACA),
    GUADALUPE_ETLA("Guadalupe Etla", Estado.OAXACA),
    GUADALUPE_DE_RAMIREZ("Guadalupe de Ramírez", Estado.OAXACA),
    GUELATAO_DE_JUAREZ("Guelatao de Juárez", Estado.OAXACA),
    GUEVEA_DE_HUMBOLDT("Guevea de Humboldt", Estado.OAXACA),
    MESONES_HIDALGO("Mesones Hidalgo", Estado.OAXACA),
    VILLA_HIDALGO("Villa Hidalgo", Estado.OAXACA),
    HEROICA_CIUDAD_DE_HUAJUAPAN_DE_LEON("Heroica Ciudad de Huajuapan de León", Estado.OAXACA),
    HUAUTEPEC("Huautepec", Estado.OAXACA),
    HUAUTLA_DE_JIMENEZ("Huautla de Jiménez", Estado.OAXACA),
    IXTLAN_DE_JUAREZ("Ixtlán de Juárez", Estado.OAXACA),
    HEROICA_CIUDAD_DE_JUCHITAN_DE_ZARAGOZA("Heroica Ciudad de Juchitán de Zaragoza", Estado.OAXACA),
    LOMA_BONITA("Loma Bonita", Estado.OAXACA),
    MAGDALENA_APASCO("Magdalena Apasco", Estado.OAXACA),
    MAGDALENA_JALTEPEC("Magdalena Jaltepec", Estado.OAXACA),
    SANTA_MAGDALENA_JICOTLAN("Santa Magdalena Jicotlán", Estado.OAXACA),
    MAGDALENA_MIXTEPEC("Magdalena Mixtepec", Estado.OAXACA),
    MAGDALENA_OCOTLAN("Magdalena Ocotlán", Estado.OAXACA),
    MAGDALENA_PENASCO("Magdalena Peñasco", Estado.OAXACA),
    MAGDALENA_TEITIPAC("Magdalena Teitipac", Estado.OAXACA),
    MAGDALENA_TEQUISISTLAN("Magdalena Tequisistlán", Estado.OAXACA),
    MAGDALENA_TLACOTEPEC("Magdalena Tlacotepec", Estado.OAXACA),
    MAGDALENA_ZAHUATLAN("Magdalena Zahuatlán", Estado.OAXACA),
    MARISCALA_DE_JUAREZ("Mariscala de Juárez", Estado.OAXACA),
    MARTIRES_DE_TACUBAYA("Mártires de Tacubaya", Estado.OAXACA),
    MATIAS_ROMERO_AVENDANO("Matías Romero Avendaño", Estado.OAXACA),
    MAZATLAN_VILLA_DE_FLORES("Mazatlán Villa de Flores", Estado.OAXACA),
    MIAHUATLAN_DE_PORFIRIO_DIAZ("Miahuatlán de Porfirio Díaz", Estado.OAXACA),
    MIXISTLAN_DE_LA_REFORMA("Mixistlán de la Reforma", Estado.OAXACA),
    MONJAS("Monjas", Estado.OAXACA),
    NATIVIDAD("Natividad", Estado.OAXACA),
    NAZARENO_ETLA("Nazareno Etla", Estado.OAXACA),
    NEJAPA_DE_MADERO("Nejapa de Madero", Estado.OAXACA),
    IXPANTEPEC_NIEVES("Ixpantepec Nieves", Estado.OAXACA),
    SANTIAGO_NILTEPEC("Santiago Niltepec", Estado.OAXACA),
    OAXACA_DE_JUAREZ("Oaxaca de Juárez", Estado.OAXACA),
    OCOTLAN_DE_MORELOS("Ocotlán de Morelos", Estado.OAXACA),
    LA_PE("La Pe", Estado.OAXACA),
    PINOTEPA_DE_DON_LUIS("Pinotepa de Don Luis", Estado.OAXACA),
    PLUMA_HIDALGO("Pluma Hidalgo", Estado.OAXACA),
    SAN_JOSE_DEL_PROGRESO("San José del Progreso", Estado.OAXACA),
    PUTLA_VILLA_DE_GUERRERO("Putla Villa de Guerrero", Estado.OAXACA),
    SANTA_CATARINA_QUIOQUITANI("Santa Catarina Quioquitani", Estado.OAXACA),
    REFORMA_DE_PINEDA("Reforma de Pineda", Estado.OAXACA),
    LA_REFORMA("La Reforma", Estado.OAXACA),
    REYES_ETLA("Reyes Etla", Estado.OAXACA),
    ROJAS_DE_CUAUHTEMOC("Rojas de Cuauhtémoc", Estado.OAXACA),
    SALINA_CRUZ("Salina Cruz", Estado.OAXACA),
    SAN_AGUSTIN_AMATENGO("San Agustín Amatengo", Estado.OAXACA),
    SAN_AGUSTIN_ATENANGO("San Agustín Atenango", Estado.OAXACA),
    SAN_AGUSTIN_CHAYUCO("San Agustín Chayuco", Estado.OAXACA),
    SAN_AGUSTIN_DE_LAS_JUNTAS("San Agustín de las Juntas", Estado.OAXACA),
    SAN_AGUSTIN_ETLA("San Agustín Etla", Estado.OAXACA),
    SAN_AGUSTIN_LOXICHA("San Agustín Loxicha", Estado.OAXACA),
    SAN_AGUSTIN_TLACOTEPEC("San Agustín Tlacotepec", Estado.OAXACA),
    SAN_AGUSTIN_YATARENI("San Agustín Yatareni", Estado.OAXACA),
    SAN_ANDRES_CABECERA_NUEVA("San Andrés Cabecera Nueva", Estado.OAXACA),
    SAN_ANDRES_DINICUITI("San Andrés Dinicuiti", Estado.OAXACA),
    SAN_ANDRES_HUAXPALTEPEC("San Andrés Huaxpaltepec", Estado.OAXACA),
    SAN_ANDRES_HUAYAPAM("San Andrés Huayápam", Estado.OAXACA),
    SAN_ANDRES_IXTLAHUACA("San Andrés Ixtlahuaca", Estado.OAXACA),
    SAN_ANDRES_LAGUNAS("San Andrés Lagunas", Estado.OAXACA),
    SAN_ANDRES_NUXINO("San Andrés Nuxiño", Estado.OAXACA),
    SAN_ANDRES_PAXTLAN("San Andrés Paxtlán", Estado.OAXACA),
    SAN_ANDRES_SINAXTLA("San Andrés Sinaxtla", Estado.OAXACA),
    SAN_ANDRES_SOLAGA("San Andrés Solaga", Estado.OAXACA),
    SAN_ANDRES_TEOTILALPAM("San Andrés Teotilálpam", Estado.OAXACA),
    SAN_ANDRES_TEPETLAPA("San Andrés Tepetlapa", Estado.OAXACA),
    SAN_ANDRES_YAA("San Andrés Yaá", Estado.OAXACA),
    SAN_ANDRES_ZABACHE("San Andrés Zabache", Estado.OAXACA),
    SAN_ANDRES_ZAUTLA("San Andrés Zautla", Estado.OAXACA),
    SAN_ANTONINO_CASTILLO_VELASCO("San Antonino Castillo Velasco", Estado.OAXACA),
    SAN_ANTONINO_EL_ALTO("San Antonino el Alto", Estado.OAXACA),
    SAN_ANTONINO_MONTE_VERDE("San Antonino Monte Verde", Estado.OAXACA),
    SAN_ANTONIO_ACUTLA("San Antonio Acutla", Estado.OAXACA),
    SAN_ANTONIO_DE_LA_CAL("San Antonio de la Cal", Estado.OAXACA),
    SAN_ANTONIO_HUITEPEC("San Antonio Huitepec", Estado.OAXACA),
    SAN_ANTONIO_NANAHUATIPAM("San Antonio Nanahuatípam", Estado.OAXACA),
    SAN_ANTONIO_SINICAHUA("San Antonio Sinicahua", Estado.OAXACA),
    SAN_ANTONIO_TEPETLAPA("San Antonio Tepetlapa", Estado.OAXACA),
    SAN_BALTAZAR_CHICHICAPAM("San Baltazar Chichicápam", Estado.OAXACA),
    SAN_BALTAZAR_LOXICHA("San Baltazar Loxicha", Estado.OAXACA),
    SAN_BALTAZAR_YATZACHI_EL_BAJO("San Baltazar Yatzachi el Bajo", Estado.OAXACA),
    SAN_BARTOLO_COYOTEPEC("San Bartolo Coyotepec", Estado.OAXACA),
    SAN_BARTOLOME_AYAUTLA("San Bartolomé Ayautla", Estado.OAXACA),
    SAN_BARTOLOME_LOXICHA("San Bartolomé Loxicha", Estado.OAXACA),
    SAN_BARTOLOME_QUIALANA("San Bartolomé Quialana", Estado.OAXACA),
    SAN_BARTOLOME_YUCUANE("San Bartolomé Yucuañe", Estado.OAXACA),
    SAN_BARTOLOME_ZOOGOCHO("San Bartolomé Zoogocho", Estado.OAXACA),
    SAN_BARTOLO_SOYALTEPEC("San Bartolo Soyaltepec", Estado.OAXACA),
    SAN_BARTOLO_YAUTEPEC("San Bartolo Yautepec", Estado.OAXACA),
    SAN_BERNARDO_MIXTEPEC("San Bernardo Mixtepec", Estado.OAXACA),
    SAN_BLAS_ATEMPA("San Blas Atempa", Estado.OAXACA),
    SAN_CARLOS_YAUTEPEC("San Carlos Yautepec", Estado.OAXACA),
    SAN_CRISTOBAL_AMATLAN("San Cristóbal Amatlán", Estado.OAXACA),
    SAN_CRISTOBAL_AMOLTEPEC("San Cristóbal Amoltepec", Estado.OAXACA),
    SAN_CRISTOBAL_LACHIRIOAG("San Cristóbal Lachirioag", Estado.OAXACA),
    SAN_CRISTOBAL_SUCHIXTLAHUACA("San Cristóbal Suchixtlahuaca", Estado.OAXACA),
    SAN_DIONISIO_DEL_MAR("San Dionisio del Mar", Estado.OAXACA),
    SAN_DIONISIO_OCOTEPEC("San Dionisio Ocotepec", Estado.OAXACA),
    SAN_DIONISIO_OCOTLAN("San Dionisio Ocotlán", Estado.OAXACA),
    SAN_ESTEBAN_ATATLAHUCA("San Esteban Atatlahuca", Estado.OAXACA),
    SAN_FELIPE_JALAPA_DE_DIAZ("San Felipe Jalapa de Díaz", Estado.OAXACA),
    SAN_FELIPE_TEJALAPAM("San Felipe Tejalápam", Estado.OAXACA),
    SAN_FELIPE_USILA("San Felipe Usila", Estado.OAXACA),
    SAN_FRANCISCO_CAHUACUA("San Francisco Cahuacuá", Estado.OAXACA),
    SAN_FRANCISCO_CAJONOS("San Francisco Cajonos", Estado.OAXACA),
    SAN_FRANCISCO_CHAPULAPA("San Francisco Chapulapa", Estado.OAXACA),
    SAN_FRANCISCO_CHINDUA("San Francisco Chindúa", Estado.OAXACA),
    SAN_FRANCISCO_DEL_MAR("San Francisco del Mar", Estado.OAXACA),
    SAN_FRANCISCO_HUEHUETLAN("San Francisco Huehuetlán", Estado.OAXACA),
    SAN_FRANCISCO_IXHUATAN("San Francisco Ixhuatán", Estado.OAXACA),
    SAN_FRANCISCO_JALTEPETONGO("San Francisco Jaltepetongo", Estado.OAXACA),
    SAN_FRANCISCO_LACHIGOLO("San Francisco Lachigoló", Estado.OAXACA),
    SAN_FRANCISCO_LOGUECHE("San Francisco Logueche", Estado.OAXACA),
    SAN_FRANCISCO_NUXANO("San Francisco Nuxaño", Estado.OAXACA),
    SAN_FRANCISCO_OZOLOTEPEC("San Francisco Ozolotepec", Estado.OAXACA),
    SAN_FRANCISCO_SOLA("San Francisco Sola", Estado.OAXACA),
    SAN_FRANCISCO_TELIXTLAHUACA("San Francisco Telixtlahuaca", Estado.OAXACA),
    SAN_FRANCISCO_TEOPAN("San Francisco Teopan", Estado.OAXACA),
    SAN_FRANCISCO_TLAPANCINGO("San Francisco Tlapancingo", Estado.OAXACA),
    SAN_GABRIEL_MIXTEPEC("San Gabriel Mixtepec", Estado.OAXACA),
    SAN_ILDEFONSO_AMATLAN("San Ildefonso Amatlán", Estado.OAXACA),
    SAN_ILDEFONSO_SOLA("San Ildefonso Sola", Estado.OAXACA),
    SAN_ILDEFONSO_VILLA_ALTA("San Ildefonso Villa Alta", Estado.OAXACA),
    SAN_JACINTO_AMILPAS("San Jacinto Amilpas", Estado.OAXACA),
    SAN_JACINTO_TLACOTEPEC("San Jacinto Tlacotepec", Estado.OAXACA),
    SAN_JERONIMO_COATLAN("San Jerónimo Coatlán", Estado.OAXACA),
    SAN_JERONIMO_SILACAYOAPILLA("San Jerónimo Silacayoapilla", Estado.OAXACA),
    SAN_JERONIMO_SOSOLA("San Jerónimo Sosola", Estado.OAXACA),
    SAN_JERONIMO_TAVICHE("San Jerónimo Taviche", Estado.OAXACA),
    SAN_JERONIMO_TECOATL("San Jerónimo Tecóatl", Estado.OAXACA),
    SAN_JORGE_NUCHITA("San Jorge Nuchita", Estado.OAXACA),
    SAN_JOSE_AYUQUILA("San José Ayuquila", Estado.OAXACA),
    SAN_JOSE_CHILTEPEC("San José Chiltepec", Estado.OAXACA),
    SAN_JOSE_DEL_PENASCO("San José del Peñasco", Estado.OAXACA),
    SAN_JOSE_ESTANCIA_GRANDE("San José Estancia Grande", Estado.OAXACA),
    SAN_JOSE_INDEPENDENCIA("San José Independencia", Estado.OAXACA),
    SAN_JOSE_LACHIGUIRI("San José Lachiguiri", Estado.OAXACA),
    SAN_JOSE_TENANGO("San José Tenango", Estado.OAXACA),
    SAN_JUAN_ACHIUTLA("San Juan Achiutla", Estado.OAXACA),
    SAN_JUAN_ATEPEC("San Juan Atepec", Estado.OAXACA),
    ANIMAS_TRUJANO("Ánimas Trujano", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_ATATLAHUCA("San Juan Bautista Atatlahuca", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_COIXTLAHUACA("San Juan Bautista Coixtlahuaca", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_CUICATLAN("San Juan Bautista Cuicatlán", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_GUELACHE("San Juan Bautista Guelache", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_JAYACATLAN("San Juan Bautista Jayacatlán", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_LO_DE_SOTO("San Juan Bautista Lo de Soto", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_SUCHITEPEC("San Juan Bautista Suchitepec", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_TLACOATZINTEPEC("San Juan Bautista Tlacoatzintepec", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_TLACHICHILCO("San Juan Bautista Tlachichilco", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_TUXTEPEC("San Juan Bautista Tuxtepec", Estado.OAXACA),
    SAN_JUAN_CACAHUATEPEC("San Juan Cacahuatepec", Estado.OAXACA),
    SAN_JUAN_CIENEGUILLA("San Juan Cieneguilla", Estado.OAXACA),
    SAN_JUAN_COATZOSPAM("San Juan Coatzóspam", Estado.OAXACA),
    SAN_JUAN_COLORADO_("San Juan Colorado ", Estado.OAXACA),
    SAN_JUAN_COMALTEPEC("San Juan Comaltepec", Estado.OAXACA),
    SAN_JUAN_COTZOCON("San Juan Cotzocón", Estado.OAXACA),
    SAN_JUAN_CHICOMEZUCHIL("San Juan Chicomezúchil", Estado.OAXACA),
    SAN_JUAN_CHILATECA("San Juan Chilateca", Estado.OAXACA),
    SAN_JUAN_DEL_ESTADO("San Juan del Estado", Estado.OAXACA),
    SAN_JUAN_DEL_RIO("San Juan del Rio", Estado.OAXACA),
    SAN_JUAN_DIUXI("San Juan Diuxi", Estado.OAXACA),
    SAN_JUAN_EVANGELISTA_ANALCO("San Juan Evangelista Analco", Estado.OAXACA),
    SAN_JUAN_GUELAVIA("San Juan Guelavía", Estado.OAXACA),
    SAN_JUAN_GUICHICOVI("San Juan Guichicovi", Estado.OAXACA),
    SAN_JUAN_IHUALTEPEC("San Juan Ihualtepec", Estado.OAXACA),
    SAN_JUAN_JUQUILA_MIXES("San Juan Juquila Mixes", Estado.OAXACA),
    SAN_JUAN_JUQUILA_VIJANOS("San Juan Juquila Vijanos", Estado.OAXACA),
    SAN_JUAN_LACHAO("San Juan Lachao", Estado.OAXACA),
    SAN_JUAN_LACHIGALLA("San Juan Lachigalla", Estado.OAXACA),
    SAN_JUAN_LAJARCIA("San Juan Lajarcia", Estado.OAXACA),
    SAN_JUAN_LALANA("San Juan Lalana", Estado.OAXACA),
    SAN_JUAN_DE_LOS_CUES("San Juan de los Cués", Estado.OAXACA),
    SAN_JUAN_MAZATLAN("San Juan Mazatlán", Estado.OAXACA),
    SAN_JUAN_MIXTEPEC_DISTRITO_08("San Juan Mixtepec Distrito 08", Estado.OAXACA),
    SAN_JUAN_MIXTEPEC_DISTRITO_26("San Juan Mixtepec Distrito 26", Estado.OAXACA),
    SAN_JUAN_NUMI("San Juan Ñumí", Estado.OAXACA),
    SAN_JUAN_OZOLOTEPEC("San Juan Ozolotepec", Estado.OAXACA),
    SAN_JUAN_PETLAPA("San Juan Petlapa", Estado.OAXACA),
    SAN_JUAN_QUIAHIJE("San Juan Quiahije", Estado.OAXACA),
    SAN_JUAN_QUIOTEPEC("San Juan Quiotepec", Estado.OAXACA),
    SAN_JUAN_SAYULTEPEC("San Juan Sayultepec", Estado.OAXACA),
    SAN_JUAN_TABAA("San Juan Tabaá", Estado.OAXACA),
    SAN_JUAN_TAMAZOLA("San Juan Tamazola", Estado.OAXACA),
    SAN_JUAN_TEITA("San Juan Teita", Estado.OAXACA),
    SAN_JUAN_TEITIPAC("San Juan Teitipac", Estado.OAXACA),
    SAN_JUAN_TEPEUXILA("San Juan Tepeuxila", Estado.OAXACA),
    SAN_JUAN_TEPOSCOLULA("San Juan Teposcolula", Estado.OAXACA),
    SAN_JUAN_YAEE("San Juan Yaeé", Estado.OAXACA),
    SAN_JUAN_YATZONA("San Juan Yatzona", Estado.OAXACA),
    SAN_JUAN_YUCUITA("San Juan Yucuita", Estado.OAXACA),
    SAN_LORENZO("San Lorenzo", Estado.OAXACA),
    SAN_LORENZO_ALBARRADAS("San Lorenzo Albarradas", Estado.OAXACA),
    SAN_LORENZO_CACAOTEPEC("San Lorenzo Cacaotepec", Estado.OAXACA),
    SAN_LORENZO_CUAUNECUILTITLA("San Lorenzo Cuaunecuiltitla", Estado.OAXACA),
    SAN_LORENZO_TEXMELUCAN("San Lorenzo Texmelúcan", Estado.OAXACA),
    SAN_LORENZO_VICTORIA("San Lorenzo Victoria", Estado.OAXACA),
    SAN_LUCAS_CAMOTLAN("San Lucas Camotlán", Estado.OAXACA),
    SAN_LUCAS_OJITLAN("San Lucas Ojitlán", Estado.OAXACA),
    SAN_LUCAS_QUIAVINI("San Lucas Quiaviní", Estado.OAXACA),
    SAN_LUCAS_ZOQUIAPAM("San Lucas Zoquiápam", Estado.OAXACA),
    SAN_LUIS_AMATLAN("San Luis Amatlán", Estado.OAXACA),
    SAN_MARCIAL_OZOLOTEPEC("San Marcial Ozolotepec", Estado.OAXACA),
    SAN_MARCOS_ARTEAGA("San Marcos Arteaga", Estado.OAXACA),
    SAN_MARTIN_DE_LOS_CANSECOS("San Martín de los Cansecos", Estado.OAXACA),
    SAN_MARTIN_HUAMELULPAM("San Martín Huamelúlpam", Estado.OAXACA),
    SAN_MARTIN_ITUNYOSO("San Martín Itunyoso", Estado.OAXACA),
    SAN_MARTIN_LACHILA("San Martín Lachilá", Estado.OAXACA),
    SAN_MARTIN_PERAS("San Martín Peras", Estado.OAXACA),
    SAN_MARTIN_TILCAJETE("San Martín Tilcajete", Estado.OAXACA),
    SAN_MARTIN_TOXPALAN("San Martín Toxpalan", Estado.OAXACA),
    SAN_MARTIN_ZACATEPEC("San Martín Zacatepec", Estado.OAXACA),
    SAN_MATEO_CAJONOS("San Mateo Cajonos", Estado.OAXACA),
    CAPULALPAM_DE_MENDEZ("Capulálpam de Méndez", Estado.OAXACA),
    SAN_MATEO_DEL_MAR("San Mateo del Mar", Estado.OAXACA),
    SAN_MATEO_YOLOXOCHITLAN("San Mateo Yoloxochitlán", Estado.OAXACA),
    SAN_MATEO_ETLATONGO("San Mateo Etlatongo", Estado.OAXACA),
    SAN_MATEO_NEJAPAM("San Mateo Nejápam", Estado.OAXACA),
    SAN_MATEO_PENASCO("San Mateo Peñasco", Estado.OAXACA),
    SAN_MATEO_PINAS("San Mateo Piñas", Estado.OAXACA),
    SAN_MATEO_RIO_HONDO("San Mateo Río Hondo", Estado.OAXACA),
    SAN_MATEO_SINDIHUI("San Mateo Sindihui", Estado.OAXACA),
    SAN_MATEO_TLAPILTEPEC("San Mateo Tlapiltepec", Estado.OAXACA),
    SAN_MELCHOR_BETAZA("San Melchor Betaza", Estado.OAXACA),
    SAN_MIGUEL_ACHIUTLA("San Miguel Achiutla", Estado.OAXACA),
    SAN_MIGUEL_AHUEHUETITLAN("San Miguel Ahuehuetitlán", Estado.OAXACA),
    SAN_MIGUEL_ALOAPAM("San Miguel Aloápam", Estado.OAXACA),
    SAN_MIGUEL_AMATITLAN("San Miguel Amatitlán", Estado.OAXACA),
    SAN_MIGUEL_AMATLAN("San Miguel Amatlán", Estado.OAXACA),
    SAN_MIGUEL_COATLAN("San Miguel Coatlán", Estado.OAXACA),
    SAN_MIGUEL_CHICAHUA("San Miguel Chicahua", Estado.OAXACA),
    SAN_MIGUEL_CHIMALAPA("San Miguel Chimalapa", Estado.OAXACA),
    SAN_MIGUEL_DEL_PUERTO("San Miguel del Puerto", Estado.OAXACA),
    SAN_MIGUEL_DEL_RIO("San Miguel del Río", Estado.OAXACA),
    SAN_MIGUEL_EJUTLA("San Miguel Ejutla", Estado.OAXACA),
    SAN_MIGUEL_EL_GRANDE("San Miguel el Grande", Estado.OAXACA),
    SAN_MIGUEL_HUAUTLA("San Miguel Huautla", Estado.OAXACA),
    SAN_MIGUEL_MIXTEPEC("San Miguel Mixtepec", Estado.OAXACA),
    SAN_MIGUEL_PANIXTLAHUACA("San Miguel Panixtlahuaca", Estado.OAXACA),
    SAN_MIGUEL_PERAS("San Miguel Peras", Estado.OAXACA),
    SAN_MIGUEL_PIEDRAS("San Miguel Piedras", Estado.OAXACA),
    SAN_MIGUEL_QUETZALTEPEC("San Miguel Quetzaltepec", Estado.OAXACA),
    SAN_MIGUEL_SANTA_FLOR("San Miguel Santa Flor", Estado.OAXACA),
    VILLA_SOLA_DE_VEGA("Villa Sola de Vega", Estado.OAXACA),
    SAN_MIGUEL_SOYALTEPEC("San Miguel Soyaltepec", Estado.OAXACA),
    SAN_MIGUEL_SUCHIXTEPEC("San Miguel Suchixtepec", Estado.OAXACA),
    VILLA_TALEA_DE_CASTRO("Villa Talea de Castro", Estado.OAXACA),
    SAN_MIGUEL_TECOMATLAN("San Miguel Tecomatlán", Estado.OAXACA),
    SAN_MIGUEL_TENANGO("San Miguel Tenango", Estado.OAXACA),
    SAN_MIGUEL_TEQUIXTEPEC("San Miguel Tequixtepec", Estado.OAXACA),
    SAN_MIGUEL_TILQUIAPAM("San Miguel Tilquiápam", Estado.OAXACA),
    SAN_MIGUEL_TLACAMAMA("San Miguel Tlacamama", Estado.OAXACA),
    SAN_MIGUEL_TLACOTEPEC("San Miguel Tlacotepec", Estado.OAXACA),
    SAN_MIGUEL_TULANCINGO("San Miguel Tulancingo", Estado.OAXACA),
    SAN_MIGUEL_YOTAO("San Miguel Yotao", Estado.OAXACA),
    SAN_NICOLAS("San Nicolás", Estado.OAXACA),
    SAN_NICOLAS_HIDALGO("San Nicolás Hidalgo", Estado.OAXACA),
    SAN_PABLO_COATLAN("San Pablo Coatlán", Estado.OAXACA),
    SAN_PABLO_CUATRO_VENADOS("San Pablo Cuatro Venados", Estado.OAXACA),
    SAN_PABLO_ETLA("San Pablo Etla", Estado.OAXACA),
    SAN_PABLO_HUITZO("San Pablo Huitzo", Estado.OAXACA),
    SAN_PABLO_HUIXTEPEC("San Pablo Huixtepec", Estado.OAXACA),
    SAN_PABLO_MACUILTIANGUIS("San Pablo Macuiltianguis", Estado.OAXACA),
    SAN_PABLO_TIJALTEPEC("San Pablo Tijaltepec", Estado.OAXACA),
    SAN_PABLO_VILLA_DE_MITLA("San Pablo Villa de Mitla", Estado.OAXACA),
    SAN_PABLO_YAGANIZA("San Pablo Yaganiza", Estado.OAXACA),
    SAN_PEDRO_AMUZGOS("San Pedro Amuzgos", Estado.OAXACA),
    SAN_PEDRO_APOSTOL("San Pedro Apóstol", Estado.OAXACA),
    SAN_PEDRO_ATOYAC("San Pedro Atoyac", Estado.OAXACA),
    SAN_PEDRO_CAJONOS("San Pedro Cajonos", Estado.OAXACA),
    SAN_PEDRO_COXCALTEPEC_CANTAROS("San Pedro Coxcaltepec Cántaros", Estado.OAXACA),
    SAN_PEDRO_COMITANCILLO("San Pedro Comitancillo", Estado.OAXACA),
    SAN_PEDRO_EL_ALTO("San Pedro el Alto", Estado.OAXACA),
    SAN_PEDRO_HUAMELULA("San Pedro Huamelula", Estado.OAXACA),
    SAN_PEDRO_HUILOTEPEC("San Pedro Huilotepec", Estado.OAXACA),
    SAN_PEDRO_IXCATLAN("San Pedro Ixcatlán", Estado.OAXACA),
    SAN_PEDRO_IXTLAHUACA("San Pedro Ixtlahuaca", Estado.OAXACA),
    SAN_PEDRO_JALTEPETONGO("San Pedro Jaltepetongo", Estado.OAXACA),
    SAN_PEDRO_JICAYAN("San Pedro Jicayán", Estado.OAXACA),
    SAN_PEDRO_JOCOTIPAC("San Pedro Jocotipac", Estado.OAXACA),
    SAN_PEDRO_JUCHATENGO("San Pedro Juchatengo", Estado.OAXACA),
    SAN_PEDRO_MARTIR("San Pedro Mártir", Estado.OAXACA),
    SAN_PEDRO_MARTIR_QUIECHAPA("San Pedro Mártir Quiechapa", Estado.OAXACA),
    SAN_PEDRO_MARTIR_YUCUXACO("San Pedro Mártir Yucuxaco", Estado.OAXACA),
    SAN_PEDRO_MIXTEPEC_DISTRITO_22("San Pedro Mixtepec Distrito 22", Estado.OAXACA),
    SAN_PEDRO_MIXTEPEC_DISTRITO_26("San Pedro Mixtepec Distrito 26", Estado.OAXACA),
    SAN_PEDRO_MOLINOS("San Pedro Molinos", Estado.OAXACA),
    SAN_PEDRO_NOPALA("San Pedro Nopala", Estado.OAXACA),
    SAN_PEDRO_OCOPETATILLO("San Pedro Ocopetatillo", Estado.OAXACA),
    SAN_PEDRO_OCOTEPEC("San Pedro Ocotepec", Estado.OAXACA),
    SAN_PEDRO_POCHUTLA("San Pedro Pochutla", Estado.OAXACA),
    SAN_PEDRO_QUIATONI("San Pedro Quiatoni", Estado.OAXACA),
    SAN_PEDRO_SOCHIAPAM("San Pedro Sochiápam", Estado.OAXACA),
    SAN_PEDRO_TAPANATEPEC("San Pedro Tapanatepec", Estado.OAXACA),
    SAN_PEDRO_TAVICHE("San Pedro Taviche", Estado.OAXACA),
    SAN_PEDRO_TEOZACOALCO("San Pedro Teozacoalco", Estado.OAXACA),
    SAN_PEDRO_TEUTILA("San Pedro Teutila", Estado.OAXACA),
    SAN_PEDRO_TIDAA("San Pedro Tidaá", Estado.OAXACA),
    SAN_PEDRO_TOPILTEPEC("San Pedro Topiltepec", Estado.OAXACA),
    SAN_PEDRO_TOTOLAPAM("San Pedro Totolápam", Estado.OAXACA),
    VILLA_DE_TUTUTEPEC("Villa de Tututepec", Estado.OAXACA),
    SAN_PEDRO_YANERI("San Pedro Yaneri", Estado.OAXACA),
    SAN_PEDRO_YOLOX("San Pedro Yólox", Estado.OAXACA),
    SAN_PEDRO_Y_SAN_PABLO_AYUTLA("San Pedro y San Pablo Ayutla", Estado.OAXACA),
    VILLA_DE_ETLA("Villa de Etla", Estado.OAXACA),
    SAN_PEDRO_Y_SAN_PABLO_TEPOSCOLULA("San Pedro y San Pablo Teposcolula", Estado.OAXACA),
    SAN_PEDRO_Y_SAN_PABLO_TEQUIXTEPEC("San Pedro y San Pablo Tequixtepec", Estado.OAXACA),
    SAN_PEDRO_YUCUNAMA("San Pedro Yucunama", Estado.OAXACA),
    SAN_RAYMUNDO_JALPAN("San Raymundo Jalpan", Estado.OAXACA),
    SAN_SEBASTIAN_ABASOLO("San Sebastián Abasolo", Estado.OAXACA),
    SAN_SEBASTIAN_COATLAN("San Sebastián Coatlán", Estado.OAXACA),
    SAN_SEBASTIAN_IXCAPA("San Sebastián Ixcapa", Estado.OAXACA),
    SAN_SEBASTIAN_NICANANDUTA("San Sebastián Nicananduta", Estado.OAXACA),
    SAN_SEBASTIAN_RIO_HONDO("San Sebastián Río Hondo", Estado.OAXACA),
    SAN_SEBASTIAN_TECOMAXTLAHUACA("San Sebastián Tecomaxtlahuaca", Estado.OAXACA),
    SAN_SEBASTIAN_TEITIPAC("San Sebastián Teitipac", Estado.OAXACA),
    SAN_SEBASTIAN_TUTLA("San Sebastián Tutla", Estado.OAXACA),
    SAN_SIMON_ALMOLONGAS("San Simón Almolongas", Estado.OAXACA),
    SAN_SIMON_ZAHUATLAN("San Simón Zahuatlán", Estado.OAXACA),
    SANTA_ANA("Santa Ana", Estado.OAXACA),
    SANTA_ANA_ATEIXTLAHUACA("Santa Ana Ateixtlahuaca", Estado.OAXACA),
    SANTA_ANA_CUAUHTEMOC("Santa Ana Cuauhtémoc", Estado.OAXACA),
    SANTA_ANA_DEL_VALLE("Santa Ana del Valle", Estado.OAXACA),
    SANTA_ANA_TAVELA("Santa Ana Tavela", Estado.OAXACA),
    SANTA_ANA_TLAPACOYAN("Santa Ana Tlapacoyan", Estado.OAXACA),
    SANTA_ANA_YARENI("Santa Ana Yareni", Estado.OAXACA),
    SANTA_ANA_ZEGACHE("Santa Ana Zegache", Estado.OAXACA),
    SANTA_CATALINA_QUIERI("Santa Catalina Quierí", Estado.OAXACA),
    SANTA_CATARINA_CUIXTLA("Santa Catarina Cuixtla", Estado.OAXACA),
    SANTA_CATARINA_IXTEPEJI("Santa Catarina Ixtepeji", Estado.OAXACA),
    SANTA_CATARINA_JUQUILA("Santa Catarina Juquila", Estado.OAXACA),
    SANTA_CATARINA_LACHATAO("Santa Catarina Lachatao", Estado.OAXACA),
    SANTA_CATARINA_LOXICHA("Santa Catarina Loxicha", Estado.OAXACA),
    SANTA_CATARINA_MECHOACAN("Santa Catarina Mechoacán", Estado.OAXACA),
    SANTA_CATARINA_MINAS("Santa Catarina Minas", Estado.OAXACA),
    SANTA_CATARINA_QUIANE("Santa Catarina Quiané", Estado.OAXACA),
    SANTA_CATARINA_TAYATA("Santa Catarina Tayata", Estado.OAXACA),
    SANTA_CATARINA_TICUA("Santa Catarina Ticuá", Estado.OAXACA),
    SANTA_CATARINA_YOSONOTU("Santa Catarina Yosonotú", Estado.OAXACA),
    SANTA_CATARINA_ZAPOQUILA("Santa Catarina Zapoquila", Estado.OAXACA),
    SANTA_CRUZ_ACATEPEC("Santa Cruz Acatepec", Estado.OAXACA),
    SANTA_CRUZ_AMILPAS("Santa Cruz Amilpas", Estado.OAXACA),
    SANTA_CRUZ_DE_BRAVO("Santa Cruz de Bravo", Estado.OAXACA),
    SANTA_CRUZ_ITUNDUJIA("Santa Cruz Itundujia", Estado.OAXACA),
    SANTA_CRUZ_MIXTEPEC("Santa Cruz Mixtepec", Estado.OAXACA),
    SANTA_CRUZ_NUNDACO("Santa Cruz Nundaco", Estado.OAXACA),
    SANTA_CRUZ_PAPALUTLA("Santa Cruz Papalutla", Estado.OAXACA),
    SANTA_CRUZ_TACACHE_DE_MINA("Santa Cruz Tacache de Mina", Estado.OAXACA),
    SANTA_CRUZ_TACAHUA("Santa Cruz Tacahua", Estado.OAXACA),
    SANTA_CRUZ_TAYATA("Santa Cruz Tayata", Estado.OAXACA),
    SANTA_CRUZ_XITLA("Santa Cruz Xitla", Estado.OAXACA),
    SANTA_CRUZ_XOXOCOTLAN("Santa Cruz Xoxocotlán", Estado.OAXACA),
    SANTA_CRUZ_ZENZONTEPEC("Santa Cruz Zenzontepec", Estado.OAXACA),
    SANTA_GERTRUDIS("Santa Gertrudis", Estado.OAXACA),
    SANTA_INES_DEL_MONTE("Santa Inés del Monte", Estado.OAXACA),
    SANTA_INES_YATZECHE("Santa Inés Yatzeche", Estado.OAXACA),
    SANTA_LUCIA_DEL_CAMINO("Santa Lucía del Camino", Estado.OAXACA),
    SANTA_LUCIA_MIAHUATLAN("Santa Lucía Miahuatlán", Estado.OAXACA),
    SANTA_LUCIA_MONTEVERDE("Santa Lucía Monteverde", Estado.OAXACA),
    SANTA_LUCIA_OCOTLAN("Santa Lucía Ocotlán", Estado.OAXACA),
    SANTA_MARIA_ALOTEPEC("Santa María Alotepec", Estado.OAXACA),
    SANTA_MARIA_APAZCO("Santa María Apazco", Estado.OAXACA),
    SANTA_MARIA_LA_ASUNCION("Santa María la Asunción", Estado.OAXACA),
    HEROICA_CIUDAD_DE_TLAXIACO("Heroica Ciudad de Tlaxiaco", Estado.OAXACA),
    AYOQUEZCO_DE_ALDAMA("Ayoquezco de Aldama", Estado.OAXACA),
    SANTA_MARIA_ATZOMPA("Santa María Atzompa", Estado.OAXACA),
    SANTA_MARIA_CAMOTLAN("Santa María Camotlán", Estado.OAXACA),
    SANTA_MARIA_COLOTEPEC("Santa María Colotepec", Estado.OAXACA),
    SANTA_MARIA_CORTIJO("Santa María Cortijo", Estado.OAXACA),
    SANTA_MARIA_COYOTEPEC("Santa María Coyotepec", Estado.OAXACA),
    SANTA_MARIA_CHACHOAPAM("Santa María Chachoápam", Estado.OAXACA),
    VILLA_DE_CHILAPA_DE_DIAZ("Villa de Chilapa de Díaz", Estado.OAXACA),
    SANTA_MARIA_CHILCHOTLA("Santa María Chilchotla", Estado.OAXACA),
    SANTA_MARIA_CHIMALAPA("Santa María Chimalapa", Estado.OAXACA),
    SANTA_MARIA_DEL_ROSARIO("Santa María del Rosario", Estado.OAXACA),
    SANTA_MARIA_DEL_TULE("Santa María del Tule", Estado.OAXACA),
    SANTA_MARIA_ECATEPEC("Santa María Ecatepec", Estado.OAXACA),
    SANTA_MARIA_GUELACE("Santa María Guelacé", Estado.OAXACA),
    SANTA_MARIA_GUIENAGATI("Santa María Guienagati", Estado.OAXACA),
    SANTA_MARIA_HUATULCO("Santa María Huatulco", Estado.OAXACA),
    SANTA_MARIA_HUAZOLOTITLAN("Santa María Huazolotitlán", Estado.OAXACA),
    SANTA_MARIA_IPALAPA("Santa María Ipalapa", Estado.OAXACA),
    SANTA_MARIA_IXCATLAN("Santa María Ixcatlán", Estado.OAXACA),
    SANTA_MARIA_JACATEPEC("Santa María Jacatepec", Estado.OAXACA),
    SANTA_MARIA_JALAPA_DEL_MARQUES("Santa María Jalapa del Marqués", Estado.OAXACA),
    SANTA_MARIA_JALTIANGUIS("Santa María Jaltianguis", Estado.OAXACA),
    SANTA_MARIA_LACHIXIO("Santa María Lachixío", Estado.OAXACA),
    SANTA_MARIA_MIXTEQUILLA("Santa María Mixtequilla", Estado.OAXACA),
    SANTA_MARIA_NATIVITAS("Santa María Nativitas", Estado.OAXACA),
    SANTA_MARIA_NDUAYACO("Santa María Nduayaco", Estado.OAXACA),
    SANTA_MARIA_OZOLOTEPEC("Santa María Ozolotepec", Estado.OAXACA),
    SANTA_MARIA_PAPALO("Santa María Pápalo", Estado.OAXACA),
    SANTA_MARIA_PENOLES("Santa María Peñoles", Estado.OAXACA),
    SANTA_MARIA_PETAPA("Santa María Petapa", Estado.OAXACA),
    SANTA_MARIA_QUIEGOLANI("Santa María Quiegolani", Estado.OAXACA),
    SANTA_MARIA_SOLA("Santa María Sola", Estado.OAXACA),
    SANTA_MARIA_TATALTEPEC("Santa María Tataltepec", Estado.OAXACA),
    SANTA_MARIA_TECOMAVACA("Santa María Tecomavaca", Estado.OAXACA),
    SANTA_MARIA_TEMAXCALAPA("Santa María Temaxcalapa", Estado.OAXACA),
    SANTA_MARIA_TEMAXCALTEPEC("Santa María Temaxcaltepec", Estado.OAXACA),
    SANTA_MARIA_TEOPOXCO("Santa María Teopoxco", Estado.OAXACA),
    SANTA_MARIA_TEPANTLALI("Santa María Tepantlali", Estado.OAXACA),
    SANTA_MARIA_TEXCATITLAN("Santa María Texcatitlán", Estado.OAXACA),
    SANTA_MARIA_TLAHUITOLTEPEC("Santa María Tlahuitoltepec", Estado.OAXACA),
    SANTA_MARIA_TLALIXTAC("Santa María Tlalixtac", Estado.OAXACA),
    SANTA_MARIA_TONAMECA("Santa María Tonameca", Estado.OAXACA),
    SANTA_MARIA_TOTOLAPILLA("Santa María Totolapilla", Estado.OAXACA),
    SANTA_MARIA_XADANI("Santa María Xadani", Estado.OAXACA),
    SANTA_MARIA_YALINA("Santa María Yalina", Estado.OAXACA),
    SANTA_MARIA_YAVESIA("Santa María Yavesía", Estado.OAXACA),
    SANTA_MARIA_YOLOTEPEC("Santa María Yolotepec", Estado.OAXACA),
    SANTA_MARIA_YOSOYUA("Santa María Yosoyúa", Estado.OAXACA),
    SANTA_MARIA_YUCUHITI("Santa María Yucuhiti", Estado.OAXACA),
    SANTA_MARIA_ZACATEPEC("Santa María Zacatepec", Estado.OAXACA),
    SANTA_MARIA_ZANIZA("Santa María Zaniza", Estado.OAXACA),
    SANTA_MARIA_ZOQUITLAN("Santa María Zoquitlán", Estado.OAXACA),
    SANTIAGO_AMOLTEPEC("Santiago Amoltepec", Estado.OAXACA),
    SANTIAGO_APOALA("Santiago Apoala", Estado.OAXACA),
    SANTIAGO_APOSTOL("Santiago Apóstol", Estado.OAXACA),
    SANTIAGO_ASTATA("Santiago Astata", Estado.OAXACA),
    SANTIAGO_ATITLAN("Santiago Atitlán", Estado.OAXACA),
    SANTIAGO_AYUQUILILLA("Santiago Ayuquililla", Estado.OAXACA),
    SANTIAGO_CACALOXTEPEC("Santiago Cacaloxtepec", Estado.OAXACA),
    SANTIAGO_CAMOTLAN("Santiago Camotlán", Estado.OAXACA),
    SANTIAGO_COMALTEPEC("Santiago Comaltepec", Estado.OAXACA),
    SANTIAGO_CHAZUMBA("Santiago Chazumba", Estado.OAXACA),
    SANTIAGO_CHOAPAM("Santiago Choápam", Estado.OAXACA),
    SANTIAGO_DEL_RIO("Santiago del Río", Estado.OAXACA),
    SANTIAGO_HUAJOLOTITLAN("Santiago Huajolotitlán", Estado.OAXACA),
    SANTIAGO_HUAUCLILLA("Santiago Huauclilla", Estado.OAXACA),
    SANTIAGO_IHUITLAN_PLUMAS("Santiago Ihuitlán Plumas", Estado.OAXACA),
    SANTIAGO_IXCUINTEPEC("Santiago Ixcuintepec", Estado.OAXACA),
    SANTIAGO_IXTAYUTLA("Santiago Ixtayutla", Estado.OAXACA),
    SANTIAGO_JAMILTEPEC("Santiago Jamiltepec", Estado.OAXACA),
    SANTIAGO_JOCOTEPEC("Santiago Jocotepec", Estado.OAXACA),
    SANTIAGO_JUXTLAHUACA("Santiago Juxtlahuaca", Estado.OAXACA),
    SANTIAGO_LACHIGUIRI("Santiago Lachiguiri", Estado.OAXACA),
    SANTIAGO_LALOPA("Santiago Lalopa", Estado.OAXACA),
    SANTIAGO_LAOLLAGA("Santiago Laollaga", Estado.OAXACA),
    SANTIAGO_LAXOPA("Santiago Laxopa", Estado.OAXACA),
    SANTIAGO_LLANO_GRANDE("Santiago Llano Grande", Estado.OAXACA),
    SANTIAGO_MATATLAN("Santiago Matatlán", Estado.OAXACA),
    SANTIAGO_MILTEPEC("Santiago Miltepec", Estado.OAXACA),
    SANTIAGO_MINAS("Santiago Minas", Estado.OAXACA),
    SANTIAGO_NACALTEPEC("Santiago Nacaltepec", Estado.OAXACA),
    SANTIAGO_NEJAPILLA("Santiago Nejapilla", Estado.OAXACA),
    SANTIAGO_NUNDICHE("Santiago Nundiche", Estado.OAXACA),
    SANTIAGO_NUYOO("Santiago Nuyoó", Estado.OAXACA),
    SANTIAGO_PINOTEPA_NACIONAL("Santiago Pinotepa Nacional", Estado.OAXACA),
    SANTIAGO_SUCHILQUITONGO("Santiago Suchilquitongo", Estado.OAXACA),
    SANTIAGO_TAMAZOLA("Santiago Tamazola", Estado.OAXACA),
    SANTIAGO_TAPEXTLA("Santiago Tapextla", Estado.OAXACA),
    VILLA_TEJUPAM_DE_LA_UNION("Villa Tejúpam de la Unión", Estado.OAXACA),
    SANTIAGO_TENANGO("Santiago Tenango", Estado.OAXACA),
    SANTIAGO_TEPETLAPA("Santiago Tepetlapa", Estado.OAXACA),
    SANTIAGO_TETEPEC("Santiago Tetepec", Estado.OAXACA),
    SANTIAGO_TEXCALCINGO("Santiago Texcalcingo", Estado.OAXACA),
    SANTIAGO_TEXTITLAN("Santiago Textitlán", Estado.OAXACA),
    SANTIAGO_TILANTONGO("Santiago Tilantongo", Estado.OAXACA),
    SANTIAGO_TILLO("Santiago Tillo", Estado.OAXACA),
    SANTIAGO_TLAZOYALTEPEC("Santiago Tlazoyaltepec", Estado.OAXACA),
    SANTIAGO_XANICA("Santiago Xanica", Estado.OAXACA),
    SANTIAGO_XIACUI("Santiago Xiacuí", Estado.OAXACA),
    SANTIAGO_YAITEPEC("Santiago Yaitepec", Estado.OAXACA),
    SANTIAGO_YAVEO("Santiago Yaveo", Estado.OAXACA),
    SANTIAGO_YOLOMECATL("Santiago Yolomécatl", Estado.OAXACA),
    SANTIAGO_YOSONDUA("Santiago Yosondúa", Estado.OAXACA),
    SANTIAGO_YUCUYACHI("Santiago Yucuyachi", Estado.OAXACA),
    SANTIAGO_ZACATEPEC("Santiago Zacatepec", Estado.OAXACA),
    SANTIAGO_ZOOCHILA("Santiago Zoochila", Estado.OAXACA),
    NUEVO_ZOQUIAPAM("Nuevo Zoquiápam", Estado.OAXACA),
    SANTO_DOMINGO_INGENIO("Santo Domingo Ingenio", Estado.OAXACA),
    SANTO_DOMINGO_ALBARRADAS("Santo Domingo Albarradas", Estado.OAXACA),
    SANTO_DOMINGO_ARMENTA("Santo Domingo Armenta", Estado.OAXACA),
    SANTO_DOMINGO_CHIHUITAN("Santo Domingo Chihuitán", Estado.OAXACA),
    SANTO_DOMINGO_DE_MORELOS("Santo Domingo de Morelos", Estado.OAXACA),
    SANTO_DOMINGO_IXCATLAN("Santo Domingo Ixcatlán", Estado.OAXACA),
    SANTO_DOMINGO_NUXAA("Santo Domingo Nuxaá", Estado.OAXACA),
    SANTO_DOMINGO_OZOLOTEPEC("Santo Domingo Ozolotepec", Estado.OAXACA),
    SANTO_DOMINGO_PETAPA("Santo Domingo Petapa", Estado.OAXACA),
    SANTO_DOMINGO_ROAYAGA("Santo Domingo Roayaga", Estado.OAXACA),
    SANTO_DOMINGO_TEHUANTEPEC("Santo Domingo Tehuantepec", Estado.OAXACA),
    SANTO_DOMINGO_TEOJOMULCO("Santo Domingo Teojomulco", Estado.OAXACA),
    SANTO_DOMINGO_TEPUXTEPEC("Santo Domingo Tepuxtepec", Estado.OAXACA),
    SANTO_DOMINGO_TLATAYAPAM("Santo Domingo Tlatayápam", Estado.OAXACA),
    SANTO_DOMINGO_TOMALTEPEC("Santo Domingo Tomaltepec", Estado.OAXACA),
    SANTO_DOMINGO_TONALA("Santo Domingo Tonalá", Estado.OAXACA),
    SANTO_DOMINGO_TONALTEPEC("Santo Domingo Tonaltepec", Estado.OAXACA),
    SANTO_DOMINGO_XAGACIA("Santo Domingo Xagacía", Estado.OAXACA),
    SANTO_DOMINGO_YANHUITLAN("Santo Domingo Yanhuitlán", Estado.OAXACA),
    SANTO_DOMINGO_YODOHINO("Santo Domingo Yodohino", Estado.OAXACA),
    SANTO_DOMINGO_ZANATEPEC("Santo Domingo Zanatepec", Estado.OAXACA),
    SANTOS_REYES_NOPALA("Santos Reyes Nopala", Estado.OAXACA),
    SANTOS_REYES_PAPALO("Santos Reyes Pápalo", Estado.OAXACA),
    SANTOS_REYES_TEPEJILLO("Santos Reyes Tepejillo", Estado.OAXACA),
    SANTOS_REYES_YUCUNA("Santos Reyes Yucuná", Estado.OAXACA),
    SANTO_TOMAS_JALIEZA("Santo Tomás Jalieza", Estado.OAXACA),
    SANTO_TOMAS_MAZALTEPEC("Santo Tomás Mazaltepec", Estado.OAXACA),
    SANTO_TOMAS_OCOTEPEC("Santo Tomás Ocotepec", Estado.OAXACA),
    SANTO_TOMAS_TAMAZULAPAN("Santo Tomás Tamazulapan", Estado.OAXACA),
    SAN_VICENTE_COATLAN("San Vicente Coatlán", Estado.OAXACA),
    SAN_VICENTE_LACHIXIO("San Vicente Lachixío", Estado.OAXACA),
    SAN_VICENTE_NUNU("San Vicente Nuñú", Estado.OAXACA),
    SILACAYOAPAM("Silacayoápam", Estado.OAXACA),
    SITIO_DE_XITLAPEHUA("Sitio de Xitlapehua", Estado.OAXACA),
    SOLEDAD_ETLA("Soledad Etla", Estado.OAXACA),
    VILLA_DE_TAMAZULAPAM_DEL_PROGRESO("Villa de Tamazulápam del Progreso", Estado.OAXACA),
    TANETZE_DE_ZARAGOZA("Tanetze de Zaragoza", Estado.OAXACA),
    TANICHE("Taniche", Estado.OAXACA),
    TATALTEPEC_DE_VALDES("Tataltepec de Valdés", Estado.OAXACA),
    TEOCOCUILCO_DE_MARCOS_PEREZ("Teococuilco de Marcos Pérez", Estado.OAXACA),
    TEOTITLAN_DE_FLORES_MAGON("Teotitlán de Flores Magón", Estado.OAXACA),
    TEOTITLAN_DEL_VALLE("Teotitlán del Valle", Estado.OAXACA),
    TEOTONGO("Teotongo", Estado.OAXACA),
    TEPELMEME_VILLA_DE_MORELOS("Tepelmeme Villa de Morelos", Estado.OAXACA),
    HEROICA_VILLA_TEZOATLAN_DE_SEGURA_Y_LUNA("Heroica Villa Tezoatlán de Segura y Luna", Estado.OAXACA),
    SAN_JERONIMO_TLACOCHAHUAYA("San Jerónimo Tlacochahuaya", Estado.OAXACA),
    TLACOLULA_DE_MATAMOROS("Tlacolula de Matamoros", Estado.OAXACA),
    TLACOTEPEC_PLUMAS("Tlacotepec Plumas", Estado.OAXACA),
    TLALIXTAC_DE_CABRERA("Tlalixtac de Cabrera", Estado.OAXACA),
    TOTONTEPEC_VILLA_DE_MORELOS("Totontepec Villa de Morelos", Estado.OAXACA),
    TRINIDAD_ZAACHILA("Trinidad Zaachila", Estado.OAXACA),
    LA_TRINIDAD_VISTA_HERMOSA("La Trinidad Vista Hermosa", Estado.OAXACA),
    UNION_HIDALGO("Unión Hidalgo", Estado.OAXACA),
    VALERIO_TRUJANO("Valerio Trujano", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_VALLE_NACIONAL("San Juan Bautista Valle Nacional", Estado.OAXACA),
    VILLA_DIAZ_ORDAZ("Villa Díaz Ordaz", Estado.OAXACA),
    YAXE("Yaxe", Estado.OAXACA),
    MAGDALENA_YODOCONO_DE_PORFIRIO_DIAZ("Magdalena Yodocono de Porfirio Díaz", Estado.OAXACA),
    YOGANA("Yogana", Estado.OAXACA),
    YUTANDUCHI_DE_GUERRERO("Yutanduchi de Guerrero", Estado.OAXACA),
    VILLA_DE_ZAACHILA("Villa de Zaachila", Estado.OAXACA),
    SAN_MATEO_YUCUTINDOO("San Mateo Yucutindoo", Estado.OAXACA),
    ZAPOTITLAN_LAGUNAS("Zapotitlán Lagunas", Estado.OAXACA),
    ZAPOTITLAN_PALMAS("Zapotitlán Palmas", Estado.OAXACA),
    SANTA_INES_DE_ZARAGOZA("Santa Inés de Zaragoza", Estado.OAXACA),
    ZIMATLAN_DE_ALVAREZ("Zimatlán de Álvarez", Estado.OAXACA);

    private final String nombre;

    Municipio(String nombre, Estado estado) {
        this.nombre = nombre;
    }

    public String getNombre() {
        return nombre;
    }

    @Override
    public String toString() {
        return nombre;
    }

}
