package org.casa.backend.enums;

public enum Municipio{
    ABEJONES("Abejones", Estado.OAXACA),
    ACATLAN_DE_PEREZ_FIGUEROA("Acatlán de Pérez Figueroa", Estado.OAXACA),
    ANIMAS_TRUJANO("Animas Trujano", Estado.OAXACA),
    ASUNCION_CACALOTEPEC("Asunción Cacalotepec", Estado.OAXACA),
    ASUNCION_CUYOTEPEJI("Asunción Cuyotepeji", Estado.OAXACA),
    ASUNCION_IXTALTEPEC("Asunción Ixtaltepec", Estado.OAXACA),
    ASUNCION_NOCHIXTLAN("Asunción Nochixtlán", Estado.OAXACA),
    ASUNCION_OCOTLAN("Asunción Ocotlán", Estado.OAXACA),
    ASUNCION_TLACOLULITA("Asunción Tlacolulita", Estado.OAXACA),
    AYOQUESCO("Ayoquezco de Aldama", Estado.OAXACA),
    AYOTZINTEPEC("Ayotzintepec", Estado.OAXACA),
    CALIHUALA("Calihualá", Estado.OAXACA),
    CANDELARIA_LOXICHA("Candelaria Loxicha", Estado.OAXACA),
    CAPULALPAM_DE_MENDEZ("Capulálpam de Méndez", Estado.OAXACA),
    CHAHUITES("Chahuites", Estado.OAXACA),
    CHALCATONGO_DE_HIDALGO("Chalcatongo de Hidalgo", Estado.OAXACA),
    CIENEGA_DE_ZIMATLAN("Ciénega de Zimatlán", Estado.OAXACA),
    CIUDAD_IXTEPEC("Ciudad Ixtepec", Estado.OAXACA),
    COATECAS_ALTAS("Coatecas Altas", Estado.OAXACA),
    COICOYAN_DE_LAS_FLORES("Coicoyán de las Flores", Estado.OAXACA),
    CONCEPCION_BUENAVISTA("Concepción Buenavista", Estado.OAXACA),
    CONCEPCION_PAPALO("Concepción Pápalo", Estado.OAXACA),
    CONSTANCIA_DEL_ROSARIO("Constancia del Rosario", Estado.OAXACA),
    CUILAPAM_DE_GUERRERO("Cuilápam de Guerrero", Estado.OAXACA),
    HEROICA_CIUDAD_DE_EJUTLA_DE_CRESPO("Heroica Ciudad de Ejutla de Crespo", Estado.OAXACA),
    HEROICA_CIUDAD_DE_HUAJUAPAN_DE_LEON("Heroica Ciudad de Huajuapan de León", Estado.OAXACA),
    HEROICA_CIUDAD_DE_TLAXIACO("Heroica Ciudad de Tlaxiaco", Estado.OAXACA),
    HUAUTLA_DE_JIMENEZ("Huautla de Jiménez", Estado.OAXACA),
    HUITZO("Huitzo", Estado.OAXACA),
    IXTLAN_DE_JUAREZ("Ixtlán de Juárez", Estado.OAXACA),
    JUCHITAN_DE_ZARAGOZA("Juchitán de Zaragoza", Estado.OAXACA),
    LA_COMPAÑIA("La Compañía", Estado.OAXACA),
    LA_REFORMA("La Reforma", Estado.OAXACA),
    LA_TRINIDAD_VISTA_HERMOSA("La Trinidad Vista Hermosa", Estado.OAXACA),
    LOMA_BONITA("Loma Bonita", Estado.OAXACA),
    MAGDALENA_APASCO("Magdalena Apasco", Estado.OAXACA),
    MAGDALENA_JALTEPEC("Magdalena Jaltepec", Estado.OAXACA),
    MAGDALENA_MIXTEPEC("Magdalena Mixtepec", Estado.OAXACA),
    MAGDALENA_OCOTLAN("Magdalena Ocotlán", Estado.OAXACA),
    MAGDALENA_PEJATEJEC("Magdalena Peñasco", Estado.OAXACA),
    MAGDALENA_TEHUITLANGO("Magdalena Teitipac", Estado.OAXACA),
    MAGDALENA_TLAHIUITE("Magdalena Tlacotepec", Estado.OAXACA),
    MAGDALENA_ZAHUATLAN("Magdalena Zahuatlán", Estado.OAXACA),
    MARISCALA_DE_JUAREZ("Mariscala de Juárez", Estado.OAXACA),
    MATIAS_ROMERO_AVENDAÑO("Matías Romero Avendaño", Estado.OAXACA),
    MAZATLAN_VILLA_DE_FLORES("Mazatlán Villa de Flores", Estado.OAXACA),
    MESONES_HIDALGO("Mesones Hidalgo", Estado.OAXACA),
    MIAHUATLAN_DE_PORFIRIO_DIAZ("Miahuatlán de Porfirio Díaz", Estado.OAXACA),
    MIXISTLAN_DE_LA_REFORMA("Mixistlán de la Reforma", Estado.OAXACA),
    MONJAS("Monjas", Estado.OAXACA),
    NATIVIDAD("Natividad", Estado.OAXACA),
    NAZARENO_ETLA("Nazareno Etla", Estado.OAXACA),
    NEJAPA_DE_MADERO("Nejapa de Madero", Estado.OAXACA),
    NUEVO_ZOQUIAPAM("Nuevo Zoquiápam", Estado.OAXACA),
    OAXACA_DE_JUAREZ("Oaxaca de Juárez", Estado.OAXACA),
    OCOTLAN_DE_MORELOS("Ocotlán de Morelos", Estado.OAXACA),
    PINOTEPA_DE_DON_LUIS("Pinotepa de Don Luis", Estado.OAXACA),
    PINOTEPA_NACIONAL("Pinotepa Nacional", Estado.OAXACA),
    PUTLA_VILLA_DE_GUERRERO("Putla Villa de Guerrero", Estado.OAXACA),
    REFORMA_DE_PINEDA("Reforma de Pineda", Estado.OAXACA),
    REYES_ETLA("Reyes Etla", Estado.OAXACA),
    RIO_GRANDE("Río Grande", Estado.OAXACA),
    SALINA_CRUZ("Salina Cruz", Estado.OAXACA),
    SAN_AGUSTIN_AMATENGO("San Agustín Amatengo", Estado.OAXACA),
    SAN_AGUSTIN_ATENANGO("San Agustín Atenango", Estado.OAXACA),
    SAN_AGUSTIN_CHAYUCO("San Agustín Chayuco", Estado.OAXACA),
    SAN_AGUSTIN_DE_LAS_JUNTAS("San Agustín de las Juntas", Estado.OAXACA),
    SAN_AGUSTIN_ETLA("San Agustín Etla", Estado.OAXACA),
    SAN_AGUSTIN_LOXICHA("San Agustín Loxicha", Estado.OAXACA),
    SAN_AGUSTIN_TLACOTEPEC("San Agustín Tlacotepec", Estado.OAXACA),
    SAN_AGUSTIN_YATARENI("San Agustín Yatareni", Estado.OAXACA),
    SAN_ANDRES_CABECERA_NUEVA("San Andrés Cabecera Nueva", Estado.OAXACA),
    SAN_ANDRES_DINICUITI("San Andrés Dinicuiti", Estado.OAXACA),
    SAN_ANDRES_HUAXPALTEPEC("San Andrés Huaxpaltepec", Estado.OAXACA),
    SAN_ANDRES_HUAYAPAM("San Andrés Huayápam", Estado.OAXACA),
    SAN_ANDRES_IXTLAHUACA("San Andrés Ixtlahuaca", Estado.OAXACA),
    SAN_ANDRES_LAGUNAS("San Andrés Lagunas", Estado.OAXACA),
    SAN_ANDRES_NUXIÑO("San Andrés Nuxiño", Estado.OAXACA),
    SAN_ANDRES_PAXILA("San Andrés Paxtlán", Estado.OAXACA),
    SAN_ANDRES_SINAXTLA("San Andrés Sinaxtla", Estado.OAXACA),
    SAN_ANDRES_SOLAGA("San Andrés Solaga", Estado.OAXACA),
    SAN_ANDRES_TEOTILALPAM("San Andrés Teotilálpam", Estado.OAXACA),
    SAN_ANDRES_TEPETLAPA("San Andrés Tepetlapa", Estado.OAXACA),
    SAN_ANDRES_YAÁ("San Andrés Yaá", Estado.OAXACA),
    SAN_ANDRES_ZAUTLA("San Andrés Zautla", Estado.OAXACA),
    SAN_ANTONINO_CASTILLO_VELASCO("San Antonino Castillo Velasco", Estado.OAXACA),
    SAN_ANTONINO_EL_ALTO("San Antonino el Alto", Estado.OAXACA),
    SAN_ANTONINO_MONTE_VERDE("San Antonino Monte Verde", Estado.OAXACA),
    SAN_ANTONIO_ACUTLA("San Antonio Acutla", Estado.OAXACA),
    SAN_ANTONIO_DE_LA_CAL("San Antonio de la Cal", Estado.OAXACA),
    SAN_ANTONIO_HUITEPEC("San Antonio Huitepec", Estado.OAXACA),
    SAN_ANTONIO_NANAHUATIPAM("San Antonio Nanahuatípam", Estado.OAXACA),
    SAN_ANTONIO_SINICAHUA("San Antonio Sinicahua", Estado.OAXACA),
    SAN_ANTONIO_TEPETLAPA("San Antonio Tepetlapa", Estado.OAXACA),
    SAN_BALTASAR_CHICHICAPAM("San Baltazar Chichicápam", Estado.OAXACA),
    SAN_BALTASAR_LOXICHA("San Baltazar Loxicha", Estado.OAXACA),
    SAN_BALTASAR_YATZACHI_EL_BAJO("San Baltazar Yatzachi el Bajo", Estado.OAXACA),
    SAN_BARTOLO_COYOTEPEC("San Bartolo Coyotepec", Estado.OAXACA),
    SAN_BARTOLOME_AYAUTLA("San Bartolomé Ayautla", Estado.OAXACA),
    SAN_BARTOLOME_LOXICHA("San Bartolomé Loxicha", Estado.OAXACA),
    SAN_BARTOLOME_QUIALANA("San Bartolomé Quialana", Estado.OAXACA),
    SAN_BARTOLOME_YUCUAÑE("San Bartolomé Yucuañe", Estado.OAXACA),
    SAN_BARTOLOME_ZOOGOCHO("San Bartolomé Zoogocho", Estado.OAXACA),
    SAN_BARTOLO_SOYALTEPEC("San Bartolo Soyaltepec", Estado.OAXACA),
    SAN_BARTOLO_YAUTEPEC("San Bartolo Yautepec", Estado.OAXACA),
    SAN_BERNARDO_MIXTEPEC("San Bernardo Mixtepec", Estado.OAXACA),
    SAN_BLAS_ATEMPA("San Blas Atempa", Estado.OAXACA),
    SAN_CARLOS_YAUTEPEC("San Carlos Yautepec", Estado.OAXACA),
    SAN_CRISTOBAL_AMATLAN("San Cristóbal Amatlán", Estado.OAXACA),
    SAN_CRISTOBAL_AMOLTEPEC("San Cristóbal Amoltepec", Estado.OAXACA),
    SAN_CRISTOBAL_LACHIRIOAG("San Cristóbal Lachirioag", Estado.OAXACA),
    SAN_CRISTOBAL_SUCHIXTLAHUACA("San Cristóbal Suchixtlahuaca", Estado.OAXACA),
    SAN_DIONISIO_DEL_MAR("San Dionisio del Mar", Estado.OAXACA),
    SAN_DIONISIO_OCOTEPEC("San Dionisio Ocotepec", Estado.OAXACA),
    SAN_DIONISIO_OCOTLAN("San Dionisio Ocotlán", Estado.OAXACA),
    SAN_ESTEBAN_ATATLAHUCA("San Esteban Atatlahuca", Estado.OAXACA),
    SAN_FELIPE_JALAPA_DE_DIAZ("San Felipe Jalapa de Díaz", Estado.OAXACA),
    SAN_FELIPE_USILA("San Felipe Usila", Estado.OAXACA),
    SAN_FRANCISCO_CAHUACUA("San Francisco Cahuacuá", Estado.OAXACA),
    SAN_FRANCISCO_CAJONOS("San Francisco Cajonos", Estado.OAXACA),
    SAN_FRANCISCO_CHAPULAPA("San Francisco Chapulapa", Estado.OAXACA),
    SAN_FRANCISCO_CHINDUA("San Francisco Chindúa", Estado.OAXACA),
    SAN_FRANCISCO_DEL_MAR("San Francisco del Mar", Estado.OAXACA),
    SAN_FRANCISCO_HUEHUETLAN("San Francisco Huehuetlán", Estado.OAXACA),
    SAN_FRANCISCO_IXHUATAN("San Francisco Ixhuatán", Estado.OAXACA),
    SAN_FRANCISCO_JALTEPETONGO("San Francisco Jaltepetongo", Estado.OAXACA),
    SAN_FRANCISCO_LACHIGOLO("San Francisco Lachigoló", Estado.OAXACA),
    SAN_FRANCISCO_LOXICHA("San Francisco Loxicha", Estado.OAXACA),
    SAN_FRANCISCO_NUXAÑO("San Francisco Nuxaño", Estado.OAXACA),
    SAN_FRANCISCO_OXOTEPEC("San Francisco Ozolotepec", Estado.OAXACA),
    SAN_FRANCISCO_SOLA("San Francisco Sola", Estado.OAXACA),
    SAN_FRANCISCO_TELIXTLAHUACA("San Francisco Telixtlahuaca", Estado.OAXACA),
    SAN_FRANCISCO_TEPETLAPA("San Francisco Tepetlapa", Estado.OAXACA),
    SAN_GABRIEL_MIXTEPEC("San Gabriel Mixtepec", Estado.OAXACA),
    SAN_ILDEFONSO_AMATLAN("San Ildefonso Amatlán", Estado.OAXACA),
    SAN_ILDEFONSO_SOLA("San Ildefonso Sola", Estado.OAXACA),
    SAN_ILDEFONSO_VILLA_ALTA("San Ildefonso Villa Alta", Estado.OAXACA),
    SAN_JACINTO_AMILPAS("San Jacinto Amilpas", Estado.OAXACA),
    SAN_JACINTO_TLACOTEPEC("San Jacinto Tlacotepec", Estado.OAXACA),
    SAN_JERONIMO_COATLAN("San Jerónimo Coatlán", Estado.OAXACA),
    SAN_JERONIMO_SILACAYOAPILLA("San Jerónimo Silacayoapilla", Estado.OAXACA),
    SAN_JERONIMO_SOSOLA("San Jerónimo Sosola", Estado.OAXACA),
    SAN_JERONIMO_TAVICHE("San Jerónimo Taviche", Estado.OAXACA),
    SAN_JERONIMO_TECOATL("San Jerónimo Tecóatl", Estado.OAXACA),
    SAN_JORGE_NUCHITA("San Jorge Nuchita", Estado.OAXACA),
    SAN_JOSE_AYUQUILA("San José Ayuquila", Estado.OAXACA),
    SAN_JOSE_CHILTEPEC("San José Chiltepec", Estado.OAXACA),
    SAN_JOSE_DEL_PENASCO("San José del Peñasco", Estado.OAXACA),
    SAN_JOSE_DEL_PROGRESO("San José del Progreso", Estado.OAXACA),
    SAN_JOSE_ESTANCIA_GRANDE("San José Estancia Grande", Estado.OAXACA),
    SAN_JOSE_INDEPENDENCIA("San José Independencia", Estado.OAXACA),
    SAN_JOSE_LACHIGUIRI("San José Lachiguiri", Estado.OAXACA),
    SAN_JOSE_TENANGO("San José Tenango", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_ATATLAHUCA("San Juan Bautista Atatlahuca", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_COIXTLAHUACA("San Juan Bautista Coixtlahuaca", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_CUICATLAN("San Juan Bautista Cuicatlán", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_GUELACHE("San Juan Bautista Guelache", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_JAYACATLAN("San Juan Bautista Jayacatlán", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_LOXICHA("San Juan Bautista Lo de Soto", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_SUCHITEPEC("San Juan Bautista Suchitepec", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_TLACOATZINTEPEC("San Juan Bautista Tlacoatzintepec", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_TLACHICHILCO("San Juan Bautista Tlachichilco", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_TUXTEPEC("San Juan Bautista Tuxtepec", Estado.OAXACA),
    SAN_JUAN_BAUTISTA_VALLE_NACIONAL("San Juan Bautista Valle Nacional", Estado.OAXACA),
    SAN_JUAN_CACAHUATEPEC("San Juan Cacahuatepec", Estado.OAXACA),
    SAN_JUAN_CIENEGUILLA("San Juan Cieneguilla", Estado.OAXACA),
    SAN_JUAN_COATZOSPAM("San Juan Coatzóspam", Estado.OAXACA),
    SAN_JUAN_COMALTEPEC("San Juan Comaltepec", Estado.OAXACA),
    SAN_JUAN_COTZOCON("San Juan Cotzocón", Estado.OAXACA),
    SAN_JUAN_CHICOMEZÚCHIL("San Juan Chicomezúchil", Estado.OAXACA),
    SAN_JUAN_CHILATECA("San Juan Chilateca", Estado.OAXACA),
    SAN_JUAN_DEL_ESTADO("San Juan del Estado", Estado.OAXACA),
    SAN_JUAN_DEL_RIO("San Juan del Río", Estado.OAXACA),
    SAN_JUAN_DIUXI("San Juan Diuxi", Estado.OAXACA),
    SAN_JUAN_GUELAVIA("San Juan Guelavía", Estado.OAXACA),
    SAN_JUAN_GUICHICOVI("San Juan Guichicovi", Estado.OAXACA),
    SAN_JUAN_HUAHUAPAN("San Juan Huahuapan", Estado.OAXACA),
    SAN_JUAN_IHUALTEPEC("San Juan Ihualtepec", Estado.OAXACA),
    SAN_JUAN_JUQUILA_VIJANOS("San Juan Juquila Vijanos", Estado.OAXACA),
    SAN_JUAN_JUQUILA_MIXES("San Juan Juquila Mixes", Estado.OAXACA),
    SAN_JUAN_LACHAO("San Juan Lachao", Estado.OAXACA),
    SAN_JUAN_LACHIGALLA("San Juan Lachigalla", Estado.OAXACA),
    SAN_JUAN_LAJARCIA("San Juan Lajarcia", Estado.OAXACA),
    SAN_JUAN_LALANA("San Juan Lalana", Estado.OAXACA),
    SAN_JUAN_MAZATLAN("San Juan Mazatlán", Estado.OAXACA),
    SAN_JUAN_MIXTEPEC("San Juan Mixtepec", Estado.OAXACA),
    SAN_JUAN_NUMI("San Juan Ñumí", Estado.OAXACA),
    SAN_JUAN_OZOLOTEPEC("San Juan Ozolotepec", Estado.OAXACA),
    SAN_JUAN_PETLAPA("San Juan Petlapa", Estado.OAXACA),
    SAN_JUAN_QUIAHIJE("San Juan Quiahije", Estado.OAXACA),
    SAN_JUAN_QUIOTEPEC("San Juan Quiotepec", Estado.OAXACA),
    SAN_JUAN_SAYULTEPEC("San Juan Sayultepec", Estado.OAXACA),
    SAN_JUAN_TABAA("San Juan Tabaá", Estado.OAXACA),
    SAN_JUAN_TAMAZOLA("San Juan Tamazola", Estado.OAXACA),
    SAN_JUAN_TEPEUXILA("San Juan Tepeuxila", Estado.OAXACA),
    SAN_JUAN_TEPOSCOLULA("San Juan Teposcolula", Estado.OAXACA),
    SAN_JUAN_YAEE("San Juan Yaeé", Estado.OAXACA),
    SAN_JUAN_YATZONA("San Juan Yatzona", Estado.OAXACA),
    SAN_JUAN_YUCUITA("San Juan Yucuita", Estado.OAXACA),
    SAN_LORENZO("San Lorenzo", Estado.OAXACA),
    SAN_LORENZO_ALBARRADAS("San Lorenzo Albarradas", Estado.OAXACA),
    SAN_LORENZO_CACAOTEPEC("San Lorenzo Cacaotepec", Estado.OAXACA),
    SAN_LORENZO_CUAUNECUILTITLA("San Lorenzo Cuaunecuiltitla", Estado.OAXACA),
    SAN_LORENZO_TEXMELUCAN("San Lorenzo Texmelúcan", Estado.OAXACA),
    SAN_LORENZO_VICTORIA("San Lorenzo Victoria", Estado.OAXACA),
    SAN_LUCAS_CAMOTLAN("San Lucas Camotlán", Estado.OAXACA),
    SAN_LUCAS_OJITLAN("San Lucas Ojitlán", Estado.OAXACA),
    SAN_LUCAS_QUIAVINI("San Lucas Quiaviní", Estado.OAXACA),
    SAN_LUCAS_ZOQUIAPAM("San Lucas Zoquiápam", Estado.OAXACA),
    SAN_LUIS_AMATLAN("San Luis Amatlán", Estado.OAXACA),
    SAN_MARCIAL_OZOLOTEPEC("San Marcial Ozolotepec", Estado.OAXACA),
    SAN_MARCOS_ARTEGA("San Marcos Arteaga", Estado.OAXACA),
    SAN_MARTIN_DE_LOS_CANSECOS("San Martín de los Cansecos", Estado.OAXACA),
    SAN_MARTIN_HUAMELULPAM("San Martín Huamelúlpam", Estado.OAXACA),
    SAN_MARTIN_ITUNYOSO("San Martín Itunyoso", Estado.OAXACA),
    SAN_MARTIN_LACHILA("San Martín Lachilá", Estado.OAXACA),
    SAN_MARTIN_PERAS("San Martín Peras", Estado.OAXACA),
    SAN_MARTIN_TILCAJETE("San Martín Tilcajete", Estado.OAXACA),
    SAN_MARTIN_TOXPALAN("San Martín Toxpalan", Estado.OAXACA),
    SAN_MARTIN_ZACATEPEC("San Martín Zacatepec", Estado.OAXACA),
    SAN_MATEO_CAJONOS("San Mateo Cajonos", Estado.OAXACA),
    SAN_MATEO_DEL_MAR("San Mateo del Mar", Estado.OAXACA),
    SAN_MATEO_ETLATONGO("San Mateo Etlatongo", Estado.OAXACA),
    SAN_MATEO_NEJAJAM("San Mateo Nejápam", Estado.OAXACA),
    SAN_MATEO_PEÑASCO("San Mateo Peñasco", Estado.OAXACA),
    SAN_MATEO_PINAS("San Mateo Piñas", Estado.OAXACA),
    SAN_MATEO_RIO_HONDO("San Mateo Río Hondo", Estado.OAXACA),
    SAN_MATEO_SINDIHUI("San Mateo Sindihui", Estado.OAXACA),
    SAN_MATEO_TLAPILTEPEC("San Mateo Tlapiltepec", Estado.OAXACA),
    SAN_MATEO_YOLOXOCHITLAN("San Mateo Yoloxochitlán", Estado.OAXACA),
    SAN_MELCHOR_BETAZA("San Melchor Betaza", Estado.OAXACA),
    SAN_MIGUEL_ACHIUTLA("San Miguel Achiutla", Estado.OAXACA),
    SAN_MIGUEL_AHUATLAN("San Miguel Ahuehuetitlán", Estado.OAXACA),
    SAN_MIGUEL_ALOAPAM("San Miguel Aloápam", Estado.OAXACA),
    SAN_MIGUEL_AMATITLAN("San Miguel Amatitlán", Estado.OAXACA),
    SAN_MIGUEL_AMATLAN("San Miguel Amatlán", Estado.OAXACA),
    SAN_MIGUEL_COATLAN("San Miguel Coatlán", Estado.OAXACA),
    SAN_MIGUEL_CHICAHUA("San Miguel Chicahua", Estado.OAXACA),
    SAN_MIGUEL_CHIMALAPAS("San Miguel Chimalapa", Estado.OAXACA),
    SAN_MIGUEL_DEL_PUERTO("San Miguel del Puerto", Estado.OAXACA),
    SAN_MIGUEL_DEL_RIO("San Miguel del Río", Estado.OAXACA),
    SAN_MIGUEL_ECATEPEC("San Miguel Ecatepec", Estado.OAXACA),
    SAN_MIGUEL_HUAUTLA("San Miguel Huautla", Estado.OAXACA),
    SAN_MIGUEL_MIXTEPEC("San Miguel Mixtepec", Estado.OAXACA),
    SAN_MIGUEL_PANIXTLAHUACA("San Miguel Panixtlahuaca", Estado.OAXACA),
    SAN_MIGUEL_PERAS("San Miguel Peras", Estado.OAXACA),
    SAN_MIGUEL_PIEDRAS("San Miguel Piedras", Estado.OAXACA),
    SAN_MIGUEL_QUETZALTEPEC("San Miguel Quetzaltepec", Estado.OAXACA),
    SAN_MIGUEL_SANTA_FLOR("San Miguel Santa Flor",Estado.OAXACA),
    SAN_MIGUEL_SOYALTEPEC("fSan Miguel Soyaltepec",Estado.OAXACA),
    SAN_MIGUEL_SUCHIXTEPEC("San Miguel Suchixtepec",Estado.OAXACA),
    VILLA_TALEA_DE_CASTRO("Villa Talea de Castro",Estado.OAXACA);

    private final String nombre;
    //private final Estado estado;

    Municipio(String nombre, Estado estado) {
        this.nombre = nombre;
        //this.estado = estado;
    }

    public String getNombre() {
        return nombre;
    }

    @Override
    public String toString() {
        return nombre;
    }

}
